// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/terraform-provider-authlete/internal/sdk/internal/utils"
	"github.com/authlete/terraform-provider-authlete/internal/sdk/models/shared"
	"net/http"
)

const (
	// IDP Server
	AuditTypesGetIdpAPIServerIdp string = "idp"
)

var AuditTypesGetIdpAPIServerList = map[string]string{
	// IDP Server
	AuditTypesGetIdpAPIServerIdp: "https://login.authlete.com",
}

type AuditTypesGetIdpAPIResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of available audit event type strings.
	Strings  []string
	IdpError *shared.IdpError
}

func (a AuditTypesGetIdpAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuditTypesGetIdpAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuditTypesGetIdpAPIResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AuditTypesGetIdpAPIResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AuditTypesGetIdpAPIResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AuditTypesGetIdpAPIResponse) GetStrings() []string {
	if a == nil {
		return nil
	}
	return a.Strings
}

func (a *AuditTypesGetIdpAPIResponse) GetIdpError() *shared.IdpError {
	if a == nil {
		return nil
	}
	return a.IdpError
}
