// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/models/shared"
	"net/http"
)

type AuthTokenGetListAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// Client Identifier (client ID or client ID alias).
	//
	ClientIdentifier *string `queryParam:"style=form,explode=true,name=clientIdentifier"`
	// Unique user ID.
	//
	Subject *string `queryParam:"style=form,explode=true,name=subject"`
	// Start index of search results (inclusive). The default value is 0.
	Start *int `queryParam:"style=form,explode=true,name=start"`
	// End index of search results (exclusive). The default value is 5.
	//
	End *int `queryParam:"style=form,explode=true,name=end"`
}

func (a *AuthTokenGetListAPIRequest) GetServiceID() string {
	if a == nil {
		return ""
	}
	return a.ServiceID
}

func (a *AuthTokenGetListAPIRequest) GetClientIdentifier() *string {
	if a == nil {
		return nil
	}
	return a.ClientIdentifier
}

func (a *AuthTokenGetListAPIRequest) GetSubject() *string {
	if a == nil {
		return nil
	}
	return a.Subject
}

func (a *AuthTokenGetListAPIRequest) GetStart() *int {
	if a == nil {
		return nil
	}
	return a.Start
}

func (a *AuthTokenGetListAPIRequest) GetEnd() *int {
	if a == nil {
		return nil
	}
	return a.End
}

type AuthTokenGetListAPIResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse          *http.Response
	TokenGetListResponse *shared.TokenGetListResponse
	Result               *shared.Result
	Headers              map[string][]string
}

func (a AuthTokenGetListAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthTokenGetListAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthTokenGetListAPIResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AuthTokenGetListAPIResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AuthTokenGetListAPIResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AuthTokenGetListAPIResponse) GetTokenGetListResponse() *shared.TokenGetListResponse {
	if a == nil {
		return nil
	}
	return a.TokenGetListResponse
}

func (a *AuthTokenGetListAPIResponse) GetResult() *shared.Result {
	if a == nil {
		return nil
	}
	return a.Result
}

func (a *AuthTokenGetListAPIResponse) GetHeaders() map[string][]string {
	if a == nil {
		return map[string][]string{}
	}
	return a.Headers
}
