// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/terraform-provider-authlete/internal/sdk/internal/utils"
	"github.com/authlete/terraform-provider-authlete/internal/sdk/models/shared"
	"net/http"
)

type AuthTokenRevokeAPIRequest struct {
	// A service ID.
	ServiceID string                    `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      shared.TokenRevokeRequest `request:"mediaType=application/json"`
}

func (a *AuthTokenRevokeAPIRequest) GetServiceID() string {
	if a == nil {
		return ""
	}
	return a.ServiceID
}

func (a *AuthTokenRevokeAPIRequest) GetBody() shared.TokenRevokeRequest {
	if a == nil {
		return shared.TokenRevokeRequest{}
	}
	return a.Body
}

type AuthTokenRevokeAPIResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Token revoked successfully
	TokenRevokeResponse *shared.TokenRevokeResponse
	Result              *shared.Result
	Headers             map[string][]string
}

func (a AuthTokenRevokeAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthTokenRevokeAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthTokenRevokeAPIResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AuthTokenRevokeAPIResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AuthTokenRevokeAPIResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AuthTokenRevokeAPIResponse) GetTokenRevokeResponse() *shared.TokenRevokeResponse {
	if a == nil {
		return nil
	}
	return a.TokenRevokeResponse
}

func (a *AuthTokenRevokeAPIResponse) GetResult() *shared.Result {
	if a == nil {
		return nil
	}
	return a.Result
}

func (a *AuthTokenRevokeAPIResponse) GetHeaders() map[string][]string {
	if a == nil {
		return map[string][]string{}
	}
	return a.Headers
}
