// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/models/shared"
	"net/http"
)

type BackchannelAuthenticationFailAPIRequest struct {
	// A service ID.
	ServiceID string                                      `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      shared.BackchannelAuthenticationFailRequest `request:"mediaType=application/json"`
}

func (b *BackchannelAuthenticationFailAPIRequest) GetServiceID() string {
	if b == nil {
		return ""
	}
	return b.ServiceID
}

func (b *BackchannelAuthenticationFailAPIRequest) GetBody() shared.BackchannelAuthenticationFailRequest {
	if b == nil {
		return shared.BackchannelAuthenticationFailRequest{}
	}
	return b.Body
}

type BackchannelAuthenticationFailAPIResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse                           *http.Response
	BackchannelAuthenticationFailResponse *shared.BackchannelAuthenticationFailResponse
	Result                                *shared.Result
	Headers                               map[string][]string
}

func (b BackchannelAuthenticationFailAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BackchannelAuthenticationFailAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BackchannelAuthenticationFailAPIResponse) GetContentType() string {
	if b == nil {
		return ""
	}
	return b.ContentType
}

func (b *BackchannelAuthenticationFailAPIResponse) GetStatusCode() int {
	if b == nil {
		return 0
	}
	return b.StatusCode
}

func (b *BackchannelAuthenticationFailAPIResponse) GetRawResponse() *http.Response {
	if b == nil {
		return nil
	}
	return b.RawResponse
}

func (b *BackchannelAuthenticationFailAPIResponse) GetBackchannelAuthenticationFailResponse() *shared.BackchannelAuthenticationFailResponse {
	if b == nil {
		return nil
	}
	return b.BackchannelAuthenticationFailResponse
}

func (b *BackchannelAuthenticationFailAPIResponse) GetResult() *shared.Result {
	if b == nil {
		return nil
	}
	return b.Result
}

func (b *BackchannelAuthenticationFailAPIResponse) GetHeaders() map[string][]string {
	if b == nil {
		return map[string][]string{}
	}
	return b.Headers
}
