// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c9e8fa683cde

package operations

import (
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/models/shared"
	"net/http"
)

type ClientSecretUpdateAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// The client ID or the client ID alias of a client.
	//
	ClientIdentifier string                           `pathParam:"style=simple,explode=false,name=clientIdentifier"`
	Body             shared.ClientSecretUpdateRequest `request:"mediaType=application/json"`
}

func (c *ClientSecretUpdateAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientSecretUpdateAPIRequest) GetClientIdentifier() string {
	if c == nil {
		return ""
	}
	return c.ClientIdentifier
}

func (c *ClientSecretUpdateAPIRequest) GetBody() shared.ClientSecretUpdateRequest {
	if c == nil {
		return shared.ClientSecretUpdateRequest{}
	}
	return c.Body
}

type ClientSecretUpdateAPIResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse                *http.Response
	ClientSecretUpdateResponse *shared.ClientSecretUpdateResponse
	Result                     *shared.Result
	Headers                    map[string][]string
}

func (c ClientSecretUpdateAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientSecretUpdateAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientSecretUpdateAPIResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *ClientSecretUpdateAPIResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *ClientSecretUpdateAPIResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *ClientSecretUpdateAPIResponse) GetClientSecretUpdateResponse() *shared.ClientSecretUpdateResponse {
	if c == nil {
		return nil
	}
	return c.ClientSecretUpdateResponse
}

func (c *ClientSecretUpdateAPIResponse) GetResult() *shared.Result {
	if c == nil {
		return nil
	}
	return c.Result
}

func (c *ClientSecretUpdateAPIResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}
