// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/terraform-provider-authlete/internal/sdk/internal/utils"
	"github.com/authlete/terraform-provider-authlete/internal/sdk/models/shared"
	"net/http"
)

type ClientAuthorizationUpdateAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// A client ID.
	//
	ClientID string                                   `pathParam:"style=simple,explode=false,name=clientId"`
	Body     *shared.ClientAuthorizationUpdateRequest `request:"mediaType=application/json"`
}

func (c ClientAuthorizationUpdateAPIRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientAuthorizationUpdateAPIRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientAuthorizationUpdateAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientAuthorizationUpdateAPIRequest) GetClientID() string {
	if c == nil {
		return ""
	}
	return c.ClientID
}

func (c *ClientAuthorizationUpdateAPIRequest) GetBody() *shared.ClientAuthorizationUpdateRequest {
	if c == nil {
		return nil
	}
	return c.Body
}

type ClientAuthorizationUpdateAPIResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse                       *http.Response
	ClientAuthorizationUpdateResponse *shared.ClientAuthorizationUpdateResponse
	Result                            *shared.Result
	Headers                           map[string][]string
}

func (c ClientAuthorizationUpdateAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientAuthorizationUpdateAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientAuthorizationUpdateAPIResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *ClientAuthorizationUpdateAPIResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *ClientAuthorizationUpdateAPIResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *ClientAuthorizationUpdateAPIResponse) GetClientAuthorizationUpdateResponse() *shared.ClientAuthorizationUpdateResponse {
	if c == nil {
		return nil
	}
	return c.ClientAuthorizationUpdateResponse
}

func (c *ClientAuthorizationUpdateAPIResponse) GetResult() *shared.Result {
	if c == nil {
		return nil
	}
	return c.Result
}

func (c *ClientAuthorizationUpdateAPIResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}
