// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 13df870e149f

package operations

import (
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/models/shared"
	"net/http"
)

type ClientGrantedScopesDeleteAPIRequest struct {
	// A service ID.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// A client ID.
	//
	ClientID string `pathParam:"style=simple,explode=false,name=clientId"`
	// Unique user ID of an end-user.
	//
	Subject string `queryParam:"style=form,explode=true,name=subject"`
}

func (c *ClientGrantedScopesDeleteAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientGrantedScopesDeleteAPIRequest) GetClientID() string {
	if c == nil {
		return ""
	}
	return c.ClientID
}

func (c *ClientGrantedScopesDeleteAPIRequest) GetSubject() string {
	if c == nil {
		return ""
	}
	return c.Subject
}

type ClientGrantedScopesDeleteAPIResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse                       *http.Response
	ClientGrantedScopesDeleteResponse *shared.ClientGrantedScopesDeleteResponse
	Result                            *shared.Result
	Headers                           map[string][]string
}

func (c ClientGrantedScopesDeleteAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientGrantedScopesDeleteAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientGrantedScopesDeleteAPIResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *ClientGrantedScopesDeleteAPIResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *ClientGrantedScopesDeleteAPIResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *ClientGrantedScopesDeleteAPIResponse) GetClientGrantedScopesDeleteResponse() *shared.ClientGrantedScopesDeleteResponse {
	if c == nil {
		return nil
	}
	return c.ClientGrantedScopesDeleteResponse
}

func (c *ClientGrantedScopesDeleteAPIResponse) GetResult() *shared.Result {
	if c == nil {
		return nil
	}
	return c.Result
}

func (c *ClientGrantedScopesDeleteAPIResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}
