// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 50e57b45e434

package operations

import (
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/models/shared"
	"net/http"
)

type ClientRegistrationAPIRequestBody struct {
	// Client metadata in JSON format that complies with [RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591)
	// (OAuth 2.0 Dynamic Client Registration Protocol).
	//
	JSON string `json:"json"`
	// The client registration access token. Used only for GET, UPDATE, and DELETE requests.
	//
	Token *string `json:"token,omitzero"`
	// The client's identifier. Used for GET, UPDATE, and DELETE requests
	//
	ClientID *string `json:"clientId,omitzero"`
}

func (c *ClientRegistrationAPIRequestBody) GetJSON() string {
	if c == nil {
		return ""
	}
	return c.JSON
}

func (c *ClientRegistrationAPIRequestBody) GetToken() *string {
	if c == nil {
		return nil
	}
	return c.Token
}

func (c *ClientRegistrationAPIRequestBody) GetClientID() *string {
	if c == nil {
		return nil
	}
	return c.ClientID
}

type ClientRegistrationAPIRequest struct {
	// A service ID.
	ServiceID string                           `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      ClientRegistrationAPIRequestBody `request:"mediaType=application/json"`
}

func (c *ClientRegistrationAPIRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientRegistrationAPIRequest) GetBody() ClientRegistrationAPIRequestBody {
	if c == nil {
		return ClientRegistrationAPIRequestBody{}
	}
	return c.Body
}

type ClientRegistrationAPIResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Client registration completed successfully
	ClientRegistrationResponse *shared.ClientRegistrationResponse
	Result                     *shared.Result
	Headers                    map[string][]string
}

func (c ClientRegistrationAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientRegistrationAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientRegistrationAPIResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *ClientRegistrationAPIResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *ClientRegistrationAPIResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *ClientRegistrationAPIResponse) GetClientRegistrationResponse() *shared.ClientRegistrationResponse {
	if c == nil {
		return nil
	}
	return c.ClientRegistrationResponse
}

func (c *ClientRegistrationAPIResponse) GetResult() *shared.Result {
	if c == nil {
		return nil
	}
	return c.Result
}

func (c *ClientRegistrationAPIResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}
