// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/models/shared"
	"net/http"
)

type ClientAuthorizationGetListAPIPostRequest struct {
	// A service ID.
	ServiceID string                                   `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      shared.ClientAuthorizationGetListRequest `request:"mediaType=application/json"`
}

func (c *ClientAuthorizationGetListAPIPostRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *ClientAuthorizationGetListAPIPostRequest) GetBody() shared.ClientAuthorizationGetListRequest {
	if c == nil {
		return shared.ClientAuthorizationGetListRequest{}
	}
	return c.Body
}

type ClientAuthorizationGetListAPIPostResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse                        *http.Response
	ClientAuthorizationGetListResponse *shared.ClientAuthorizationGetListResponse
	Result                             *shared.Result
	Headers                            map[string][]string
}

func (c ClientAuthorizationGetListAPIPostResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientAuthorizationGetListAPIPostResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientAuthorizationGetListAPIPostResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *ClientAuthorizationGetListAPIPostResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *ClientAuthorizationGetListAPIPostResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *ClientAuthorizationGetListAPIPostResponse) GetClientAuthorizationGetListResponse() *shared.ClientAuthorizationGetListResponse {
	if c == nil {
		return nil
	}
	return c.ClientAuthorizationGetListResponse
}

func (c *ClientAuthorizationGetListAPIPostResponse) GetResult() *shared.Result {
	if c == nil {
		return nil
	}
	return c.Result
}

func (c *ClientAuthorizationGetListAPIPostResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}
