// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/terraform-provider-authlete/internal/sdk/internal/utils"
	"github.com/authlete/terraform-provider-authlete/internal/sdk/models/shared"
	"net/http"
)

type GrantMAPIRequest struct {
	// A service ID.
	ServiceID string           `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      shared.GMRequest `request:"mediaType=application/json"`
}

func (g *GrantMAPIRequest) GetServiceID() string {
	if g == nil {
		return ""
	}
	return g.ServiceID
}

func (g *GrantMAPIRequest) GetBody() shared.GMRequest {
	if g == nil {
		return shared.GMRequest{}
	}
	return g.Body
}

type GrantMAPIResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Grant management completed successfully
	GMResponse *shared.GMResponse
	Result     *shared.Result
	Headers    map[string][]string
}

func (g GrantMAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GrantMAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GrantMAPIResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GrantMAPIResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GrantMAPIResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GrantMAPIResponse) GetGMResponse() *shared.GMResponse {
	if g == nil {
		return nil
	}
	return g.GMResponse
}

func (g *GrantMAPIResponse) GetResult() *shared.Result {
	if g == nil {
		return nil
	}
	return g.Result
}

func (g *GrantMAPIResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
