// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/models/shared"
	"net/http"
)

type HskCreateAPIRequest struct {
	// A service ID.
	ServiceID string                  `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      shared.HskCreateRequest `request:"mediaType=application/json"`
}

func (h *HskCreateAPIRequest) GetServiceID() string {
	if h == nil {
		return ""
	}
	return h.ServiceID
}

func (h *HskCreateAPIRequest) GetBody() shared.HskCreateRequest {
	if h == nil {
		return shared.HskCreateRequest{}
	}
	return h.Body
}

type HskCreateAPIResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// HSK created successfully
	HskCreateResponse *shared.HskCreateResponse
	Result            *shared.Result
	Headers           map[string][]string
}

func (h HskCreateAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HskCreateAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HskCreateAPIResponse) GetContentType() string {
	if h == nil {
		return ""
	}
	return h.ContentType
}

func (h *HskCreateAPIResponse) GetStatusCode() int {
	if h == nil {
		return 0
	}
	return h.StatusCode
}

func (h *HskCreateAPIResponse) GetRawResponse() *http.Response {
	if h == nil {
		return nil
	}
	return h.RawResponse
}

func (h *HskCreateAPIResponse) GetHskCreateResponse() *shared.HskCreateResponse {
	if h == nil {
		return nil
	}
	return h.HskCreateResponse
}

func (h *HskCreateAPIResponse) GetResult() *shared.Result {
	if h == nil {
		return nil
	}
	return h.Result
}

func (h *HskCreateAPIResponse) GetHeaders() map[string][]string {
	if h == nil {
		return map[string][]string{}
	}
	return h.Headers
}
