// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/terraform-provider-authlete/internal/sdk/internal/utils"
	"github.com/authlete/terraform-provider-authlete/internal/sdk/models/shared"
	"net/http"
)

type UpdateAuthorizationTicketRequest struct {
	// A service ID.
	ServiceID string                                  `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      shared.AuthorizationTicketUpdateRequest `request:"mediaType=application/json"`
}

func (u *UpdateAuthorizationTicketRequest) GetServiceID() string {
	if u == nil {
		return ""
	}
	return u.ServiceID
}

func (u *UpdateAuthorizationTicketRequest) GetBody() shared.AuthorizationTicketUpdateRequest {
	if u == nil {
		return shared.AuthorizationTicketUpdateRequest{}
	}
	return u.Body
}

type UpdateAuthorizationTicketResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Authorization ticket updated successfully
	AuthorizationTicketUpdateResponse *shared.AuthorizationTicketUpdateResponse
	Result                            *shared.Result
	Headers                           map[string][]string
}

func (u UpdateAuthorizationTicketResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAuthorizationTicketResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAuthorizationTicketResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateAuthorizationTicketResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateAuthorizationTicketResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateAuthorizationTicketResponse) GetAuthorizationTicketUpdateResponse() *shared.AuthorizationTicketUpdateResponse {
	if u == nil {
		return nil
	}
	return u.AuthorizationTicketUpdateResponse
}

func (u *UpdateAuthorizationTicketResponse) GetResult() *shared.Result {
	if u == nil {
		return nil
	}
	return u.Result
}

func (u *UpdateAuthorizationTicketResponse) GetHeaders() map[string][]string {
	if u == nil {
		return map[string][]string{}
	}
	return u.Headers
}
