// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/models/shared"
	"net/http"
)

type VciDeferredParseAPIRequest struct {
	// A service ID.
	ServiceID string                         `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      shared.VciDeferredParseRequest `request:"mediaType=application/json"`
}

func (v *VciDeferredParseAPIRequest) GetServiceID() string {
	if v == nil {
		return ""
	}
	return v.ServiceID
}

func (v *VciDeferredParseAPIRequest) GetBody() shared.VciDeferredParseRequest {
	if v == nil {
		return shared.VciDeferredParseRequest{}
	}
	return v.Body
}

type VciDeferredParseAPIResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse              *http.Response
	VciDeferredParseResponse *shared.VciDeferredParseResponse
	Result                   *shared.Result
	Headers                  map[string][]string
}

func (v VciDeferredParseAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VciDeferredParseAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VciDeferredParseAPIResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *VciDeferredParseAPIResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *VciDeferredParseAPIResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *VciDeferredParseAPIResponse) GetVciDeferredParseResponse() *shared.VciDeferredParseResponse {
	if v == nil {
		return nil
	}
	return v.VciDeferredParseResponse
}

func (v *VciDeferredParseAPIResponse) GetResult() *shared.Result {
	if v == nil {
		return nil
	}
	return v.Result
}

func (v *VciDeferredParseAPIResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}
