// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/authlete/terraform-provider-authlete/internal/sdk/internal/utils"
	"github.com/authlete/terraform-provider-authlete/internal/sdk/models/shared"
	"net/http"
)

type VciSingleParseAPIRequest struct {
	// A service ID.
	ServiceID string                       `pathParam:"style=simple,explode=false,name=serviceId"`
	Body      shared.VciSingleParseRequest `request:"mediaType=application/json"`
}

func (v *VciSingleParseAPIRequest) GetServiceID() string {
	if v == nil {
		return ""
	}
	return v.ServiceID
}

func (v *VciSingleParseAPIRequest) GetBody() shared.VciSingleParseRequest {
	if v == nil {
		return shared.VciSingleParseRequest{}
	}
	return v.Body
}

type VciSingleParseAPIResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse            *http.Response
	VciSingleParseResponse *shared.VciSingleParseResponse
	Result                 *shared.Result
	Headers                map[string][]string
}

func (v VciSingleParseAPIResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VciSingleParseAPIResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VciSingleParseAPIResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *VciSingleParseAPIResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *VciSingleParseAPIResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *VciSingleParseAPIResponse) GetVciSingleParseResponse() *shared.VciSingleParseResponse {
	if v == nil {
		return nil
	}
	return v.VciSingleParseResponse
}

func (v *VciSingleParseAPIResponse) GetResult() *shared.Result {
	if v == nil {
		return nil
	}
	return v.Result
}

func (v *VciSingleParseAPIResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}
