// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b6c12f20829f

package shared

import (
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
)

type AccessToken struct {
	// The hash of the access token.
	AccessTokenHash *string `json:"accessTokenHash,omitzero"`
	// The timestamp at which the access token will expire.
	AccessTokenExpiresAt *int64 `json:"accessTokenExpiresAt,omitzero"`
	// The hash of the refresh token.
	RefreshTokenHash *string `json:"refreshTokenHash,omitzero"`
	// The timestamp at which the refresh token will expire.
	RefreshTokenExpiresAt *int64 `json:"refreshTokenExpiresAt,omitzero"`
	// The timestamp at which the access token was first created.
	//
	CreatedAt *int64 `json:"createdAt,omitzero"`
	// The timestamp at which the access token was last refreshed using the refresh token.
	//
	LastRefreshedAt *int64 `json:"lastRefreshedAt,omitzero"`
	// The ID of the client associated with the access token.
	//
	ClientID *int64 `json:"clientId,omitzero"`
	// The subject (= unique user ID) associated with the access token.
	//
	Subject *string `json:"subject,omitzero"`
	// The grant type of the access token when the access token was created.
	//
	GrantType *GrantType `json:"grantType,omitzero"`
	// The scopes associated with the access token.
	//
	Scopes []string `json:"scopes,omitzero"`
	// The properties associated with the access token.
	//
	Properties []Property `json:"properties,omitzero"`
	// The scopes associated with the refresh token.
	//
	RefreshTokenScopes []string `json:"refreshTokenScopes,omitzero"`
}

func (a AccessToken) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccessToken) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccessToken) GetAccessTokenHash() *string {
	if a == nil {
		return nil
	}
	return a.AccessTokenHash
}

func (a *AccessToken) GetAccessTokenExpiresAt() *int64 {
	if a == nil {
		return nil
	}
	return a.AccessTokenExpiresAt
}

func (a *AccessToken) GetRefreshTokenHash() *string {
	if a == nil {
		return nil
	}
	return a.RefreshTokenHash
}

func (a *AccessToken) GetRefreshTokenExpiresAt() *int64 {
	if a == nil {
		return nil
	}
	return a.RefreshTokenExpiresAt
}

func (a *AccessToken) GetCreatedAt() *int64 {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AccessToken) GetLastRefreshedAt() *int64 {
	if a == nil {
		return nil
	}
	return a.LastRefreshedAt
}

func (a *AccessToken) GetClientID() *int64 {
	if a == nil {
		return nil
	}
	return a.ClientID
}

func (a *AccessToken) GetSubject() *string {
	if a == nil {
		return nil
	}
	return a.Subject
}

func (a *AccessToken) GetGrantType() *GrantType {
	if a == nil {
		return nil
	}
	return a.GrantType
}

func (a *AccessToken) GetScopes() []string {
	if a == nil {
		return nil
	}
	return a.Scopes
}

func (a *AccessToken) GetProperties() []Property {
	if a == nil {
		return nil
	}
	return a.Properties
}

func (a *AccessToken) GetRefreshTokenScopes() []string {
	if a == nil {
		return nil
	}
	return a.RefreshTokenScopes
}
