// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// AttachmentType - Supported attachment types. This property corresponds to the `attachments_supported`
//
//	server metadata which was added by the third implementer's draft of OpenID Connect
//	for Identity Assurance 1.0.
type AttachmentType string

const (
	AttachmentTypeEmbedded AttachmentType = "EMBEDDED"
	AttachmentTypeExternal AttachmentType = "EXTERNAL"
)

func (e AttachmentType) ToPointer() *AttachmentType {
	return &e
}
func (e *AttachmentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EMBEDDED":
		fallthrough
	case "EXTERNAL":
		*e = AttachmentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AttachmentType: %v", v)
	}
}
