// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
	"time"
)

// Status - Whether the action completed successfully or failed.
type Status string

const (
	StatusCompleted Status = "completed"
	StatusFailed    Status = "failed"
)

func (e Status) ToPointer() *Status {
	return &e
}
func (e *Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "completed":
		fallthrough
	case "failed":
		*e = Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status: %v", v)
	}
}

type AuditLogEntry struct {
	// The audit event type (e.g. service.create, security.login).
	Event *string `json:"event,omitzero"`
	// Whether the action completed successfully or failed.
	Status *Status `json:"status,omitzero"`
	// When the event occurred (ISO 8601). May be null for entries without a recorded
	// timestamp; such entries are only returned on the first page of results.
	//
	Timestamp *time.Time `json:"timestamp,omitzero"`
	// The cluster or region where the event occurred.
	Cluster *string `json:"cluster,omitzero"`
	// The API path that triggered the event.
	Path *string `json:"path,omitzero"`
	// The IP address of the client that performed the action.
	RemoteAddr *string `json:"remoteAddr,omitzero"`
	// The user agent of the client.
	UserAgent *string `json:"userAgent,omitzero"`
	// The user or token that performed the action.
	User *string `json:"user,omitzero"`
	// Additional event-specific metadata.
	Details map[string]any `json:"details,omitzero"`
}

func (a AuditLogEntry) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuditLogEntry) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuditLogEntry) GetEvent() *string {
	if a == nil {
		return nil
	}
	return a.Event
}

func (a *AuditLogEntry) GetStatus() *Status {
	if a == nil {
		return nil
	}
	return a.Status
}

func (a *AuditLogEntry) GetTimestamp() *time.Time {
	if a == nil {
		return nil
	}
	return a.Timestamp
}

func (a *AuditLogEntry) GetCluster() *string {
	if a == nil {
		return nil
	}
	return a.Cluster
}

func (a *AuditLogEntry) GetPath() *string {
	if a == nil {
		return nil
	}
	return a.Path
}

func (a *AuditLogEntry) GetRemoteAddr() *string {
	if a == nil {
		return nil
	}
	return a.RemoteAddr
}

func (a *AuditLogEntry) GetUserAgent() *string {
	if a == nil {
		return nil
	}
	return a.UserAgent
}

func (a *AuditLogEntry) GetUser() *string {
	if a == nil {
		return nil
	}
	return a.User
}

func (a *AuditLogEntry) GetDetails() map[string]any {
	if a == nil {
		return nil
	}
	return a.Details
}
