// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
)

type AuthorizationRequest struct {
	// OAuth 2.0 authorization request parameters which are the request parameters that the OAuth 2.0 authorization endpoint of
	// the authorization server implementation received from the client application.
	//
	// The value of parameters is either (1) the entire query string when the HTTP method of the request from the client application is `GET`
	// or (2) the entire entity body (which is formatted in `application/x-www-form-urlencoded`) when the HTTP method of the request from
	// the client application is `POST`.
	//
	Parameters string `json:"parameters" form:"name=parameters"`
	// The arbitrary text to be attached to the ticket that will be issued from the `/auth/authorization`
	// API.
	//
	// The text can be retrieved later by the `/auth/authorization/ticket/info` API and can be updated
	// by the `/auth/authorization/ticket/update` API.
	//
	// The text will be compressed and encrypted when it is saved in the Authlete database.
	//
	Context *string `json:"context,omitzero" form:"name=context"`
	// Options for [OAuth Client ID Metadata Document](https://datatracker.ietf.org/doc/draft-ietf-oauth-client-id-metadata-document/) (CIMD).
	//
	// These options allow per-request control over CIMD behavior, taking precedence over service-level configuration when provided.
	//
	CimdOptions *CimdOptions `json:"cimdOptions,omitzero" form:"name=cimdOptions,json"`
}

func (a AuthorizationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthorizationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthorizationRequest) GetParameters() string {
	if a == nil {
		return ""
	}
	return a.Parameters
}

func (a *AuthorizationRequest) GetContext() *string {
	if a == nil {
		return nil
	}
	return a.Context
}

func (a *AuthorizationRequest) GetCimdOptions() *CimdOptions {
	if a == nil {
		return nil
	}
	return a.CimdOptions
}
