// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 31f392d96746

package shared

type AuthorizationTicketUpdateRequest struct {
	// The ticket.
	Ticket string                  `json:"ticket" form:"name=ticket"`
	Info   AuthorizationTicketInfo `json:"info" form:"name=info,json"`
}

func (a *AuthorizationTicketUpdateRequest) GetTicket() string {
	if a == nil {
		return ""
	}
	return a.Ticket
}

func (a *AuthorizationTicketUpdateRequest) GetInfo() AuthorizationTicketInfo {
	if a == nil {
		return AuthorizationTicketInfo{}
	}
	return a.Info
}
