// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 102b56ba7eed

package shared

import (
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
)

type AuthorizationDetailsElement struct {
	// The type of this element.
	//
	// From _"OAuth 2.0 Rich Authorization Requests"_: _"The type of authorization data as a string.
	// This field MAY define which other elements are allowed in the request. This element is REQUIRED."_
	//
	// This property is always NOT `null`.
	//
	Type string `json:"type"`
	// The resources and/or resource servers. This property may be `null`.
	//
	// From _"OAuth 2.0 Rich Authorization Requests"_: _"An array of strings representing the location of
	// the resource or resource server. This is typically composed of URIs."_
	//
	// This property may be `null`.
	//
	Locations []string `json:"locations,omitzero"`
	// The actions.
	//
	// From _"OAuth 2.0 Rich Authorization Requests"_: _"An array of strings representing the kinds of actions
	// to be taken at the resource. The values of the strings are determined by the API being protected."_
	//
	// This property may be `null`.
	//
	Actions []string `json:"actions,omitzero"`
	// From _"OAuth 2.0 Rich Authorization Requests"_: _"An array of strings representing the kinds of data being requested
	// from the resource."_
	//
	// This property may be `null`.
	//
	DataTypes []string `json:"dataTypes,omitzero"`
	// The identifier of a specific resource.
	// From _"OAuth 2.0 Rich Authorization Requests"_: _"A string identifier indicating a specific resource available at the API."_
	//
	// This property may be `null`.
	//
	Identifier *string `json:"identifier,omitzero"`
	// The types or levels of privilege.
	// From "OAuth 2.0 Rich Authorization Requests": _"An array of strings representing the types or
	// levels of privilege being requested at the resource."_
	//
	// This property may be `null`.
	//
	Privileges []string `json:"privileges,omitzero"`
	// The RAR request in the JSON format excluding the pre-defined attributes such as `type` and `locations`.
	// The content and semantics are specific to the deployment and the use case implemented.
	//
	OtherFields *string `json:"otherFields,omitzero"`
}

func (a AuthorizationDetailsElement) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthorizationDetailsElement) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthorizationDetailsElement) GetType() string {
	if a == nil {
		return ""
	}
	return a.Type
}

func (a *AuthorizationDetailsElement) GetLocations() []string {
	if a == nil {
		return nil
	}
	return a.Locations
}

func (a *AuthorizationDetailsElement) GetActions() []string {
	if a == nil {
		return nil
	}
	return a.Actions
}

func (a *AuthorizationDetailsElement) GetDataTypes() []string {
	if a == nil {
		return nil
	}
	return a.DataTypes
}

func (a *AuthorizationDetailsElement) GetIdentifier() *string {
	if a == nil {
		return nil
	}
	return a.Identifier
}

func (a *AuthorizationDetailsElement) GetPrivileges() []string {
	if a == nil {
		return nil
	}
	return a.Privileges
}

func (a *AuthorizationDetailsElement) GetOtherFields() *string {
	if a == nil {
		return nil
	}
	return a.OtherFields
}
