// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type BackchannelAuthenticationIssueRequest struct {
	// The ticket issued from Authlete's `/backchannel/authentication` API.
	//
	Ticket string `json:"ticket" form:"name=ticket"`
}

func (b *BackchannelAuthenticationIssueRequest) GetTicket() string {
	if b == nil {
		return ""
	}
	return b.Ticket
}
