// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2cbfccaf5dbf

package shared

import (
	"encoding/json"
	"fmt"
)

// BackchannelAuthenticationFailRequestReason - The reason of the failure of the backchannel authentication request. This request parameter is
// not mandatory but optional. However, giving this parameter is recommended. If omitted, `SERVER_ERROR`
// is used as a reason.
type BackchannelAuthenticationFailRequestReason string

const (
	BackchannelAuthenticationFailRequestReasonAccessDenied          BackchannelAuthenticationFailRequestReason = "ACCESS_DENIED"
	BackchannelAuthenticationFailRequestReasonExpiredLoginHintToken BackchannelAuthenticationFailRequestReason = "EXPIRED_LOGIN_HINT_TOKEN"
	BackchannelAuthenticationFailRequestReasonInvalidBindingMessage BackchannelAuthenticationFailRequestReason = "INVALID_BINDING_MESSAGE"
	BackchannelAuthenticationFailRequestReasonInvalidTarget         BackchannelAuthenticationFailRequestReason = "INVALID_TARGET"
	BackchannelAuthenticationFailRequestReasonInvalidUserCode       BackchannelAuthenticationFailRequestReason = "INVALID_USER_CODE"
	BackchannelAuthenticationFailRequestReasonMissingUserCode       BackchannelAuthenticationFailRequestReason = "MISSING_USER_CODE"
	BackchannelAuthenticationFailRequestReasonServerError           BackchannelAuthenticationFailRequestReason = "SERVER_ERROR"
	BackchannelAuthenticationFailRequestReasonUnauthorizedClient    BackchannelAuthenticationFailRequestReason = "UNAUTHORIZED_CLIENT"
	BackchannelAuthenticationFailRequestReasonUnknownUserID         BackchannelAuthenticationFailRequestReason = "UNKNOWN_USER_ID"
)

func (e BackchannelAuthenticationFailRequestReason) ToPointer() *BackchannelAuthenticationFailRequestReason {
	return &e
}
func (e *BackchannelAuthenticationFailRequestReason) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACCESS_DENIED":
		fallthrough
	case "EXPIRED_LOGIN_HINT_TOKEN":
		fallthrough
	case "INVALID_BINDING_MESSAGE":
		fallthrough
	case "INVALID_TARGET":
		fallthrough
	case "INVALID_USER_CODE":
		fallthrough
	case "MISSING_USER_CODE":
		fallthrough
	case "SERVER_ERROR":
		fallthrough
	case "UNAUTHORIZED_CLIENT":
		fallthrough
	case "UNKNOWN_USER_ID":
		*e = BackchannelAuthenticationFailRequestReason(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BackchannelAuthenticationFailRequestReason: %v", v)
	}
}

type BackchannelAuthenticationFailRequest struct {
	// The ticket which should be deleted on a call of Authlete's `/backchannel/authentication/fail` API.
	// This request parameter is not mandatory but optional. If this request parameter is given and the
	// ticket belongs to the service, the specified ticket is deleted from the database. Giving this
	// parameter is recommended to clean up the storage area for the service.
	//
	Ticket string `json:"ticket" form:"name=ticket"`
	// The reason of the failure of the backchannel authentication request. This request parameter is
	// not mandatory but optional. However, giving this parameter is recommended. If omitted, `SERVER_ERROR`
	// is used as a reason.
	//
	Reason BackchannelAuthenticationFailRequestReason `json:"reason" form:"name=reason"`
	// The description of the error. This corresponds to the `error_description` property in the response
	// to the client.
	//
	ErrorDescription *string `json:"errorDescription,omitzero" form:"name=errorDescription"`
	// The URI of a document which describes the error in detail. If this optional request parameter
	// is given, its value is used as the value of the `error_uri` property.
	//
	ErrorURI *string `json:"errorUri,omitzero" form:"name=errorUri"`
}

func (b *BackchannelAuthenticationFailRequest) GetTicket() string {
	if b == nil {
		return ""
	}
	return b.Ticket
}

func (b *BackchannelAuthenticationFailRequest) GetReason() BackchannelAuthenticationFailRequestReason {
	if b == nil {
		return BackchannelAuthenticationFailRequestReason("")
	}
	return b.Reason
}

func (b *BackchannelAuthenticationFailRequest) GetErrorDescription() *string {
	if b == nil {
		return nil
	}
	return b.ErrorDescription
}

func (b *BackchannelAuthenticationFailRequest) GetErrorURI() *string {
	if b == nil {
		return nil
	}
	return b.ErrorURI
}
