// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/authlete/terraform-provider-authlete/internal/sdk/internal/utils"
)

type ClientExtensionRequestableScopesGetResponse struct {
	// The requestable scopes for this client. This is null if the Requestable Scopes per Client feature is not enabled for this client.
	//
	RequestableScopes []string `json:"requestableScopes,omitzero"`
}

func (c ClientExtensionRequestableScopesGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientExtensionRequestableScopesGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientExtensionRequestableScopesGetResponse) GetRequestableScopes() []string {
	if c == nil {
		return nil
	}
	return c.RequestableScopes
}
