// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/authlete/terraform-provider-authlete/internal/sdk/internal/utils"
)

type ClientAuthorizationDeleteResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// A short message which explains the result of the API call.
	ServiceAPIKey *int64 `json:"serviceApiKey,omitzero"`
	// Get the client ID.
	ClientID *int64 `json:"clientId,omitzero"`
	// Get the subject (= unique identifier) of the user
	// who has granted authorization to the client.
	//
	Subject *string `json:"subject,omitzero"`
	// Get the scopes granted to the client application by the last
	// authorization process by the user (who is identified by the
	// subject).
	//
	LatestGrantedScopes []string `json:"latestGrantedScopes,omitzero"`
	// Get the scopes granted to the client application by all the
	// past authorization processes. Note that revoked scopes are
	// not included.
	//
	MergedGrantedScopes []string `json:"mergedGrantedScopes,omitzero"`
	// Get the timestamp in milliseconds since Unix epoch
	// at which this record was modified.
	//
	ModifiedAt *int64 `json:"modifiedAt,omitzero"`
}

func (c ClientAuthorizationDeleteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientAuthorizationDeleteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientAuthorizationDeleteResponse) GetResultCode() *string {
	if c == nil {
		return nil
	}
	return c.ResultCode
}

func (c *ClientAuthorizationDeleteResponse) GetResultMessage() *string {
	if c == nil {
		return nil
	}
	return c.ResultMessage
}

func (c *ClientAuthorizationDeleteResponse) GetServiceAPIKey() *int64 {
	if c == nil {
		return nil
	}
	return c.ServiceAPIKey
}

func (c *ClientAuthorizationDeleteResponse) GetClientID() *int64 {
	if c == nil {
		return nil
	}
	return c.ClientID
}

func (c *ClientAuthorizationDeleteResponse) GetSubject() *string {
	if c == nil {
		return nil
	}
	return c.Subject
}

func (c *ClientAuthorizationDeleteResponse) GetLatestGrantedScopes() []string {
	if c == nil {
		return nil
	}
	return c.LatestGrantedScopes
}

func (c *ClientAuthorizationDeleteResponse) GetMergedGrantedScopes() []string {
	if c == nil {
		return nil
	}
	return c.MergedGrantedScopes
}

func (c *ClientAuthorizationDeleteResponse) GetModifiedAt() *int64 {
	if c == nil {
		return nil
	}
	return c.ModifiedAt
}
