// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: eb2579c1a258

package shared

type ClientFlagUpdateResponse struct {
	// The code which represents the result of the API call.
	ResultCode string `json:"resultCode"`
	// A short message which explains the result of the API call.
	ResultMessage string `json:"resultMessage"`
}

func (c *ClientFlagUpdateResponse) GetResultCode() string {
	if c == nil {
		return ""
	}
	return c.ResultCode
}

func (c *ClientFlagUpdateResponse) GetResultMessage() string {
	if c == nil {
		return ""
	}
	return c.ResultMessage
}
