// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d1ed87700653

package shared

import (
	"encoding/json"
	"fmt"
)

// ClientAuthMethod - The client authentication method that the client application declares that it uses at the token
// endpoint. This property corresponds to `token_endpoint_auth_method` in [OpenID Connect Dynamic
// Client Registration 1.0, 2. Client Metadata](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata).
type ClientAuthMethod string

const (
	ClientAuthMethodNone                    ClientAuthMethod = "NONE"
	ClientAuthMethodClientSecretBasic       ClientAuthMethod = "CLIENT_SECRET_BASIC"
	ClientAuthMethodClientSecretPost        ClientAuthMethod = "CLIENT_SECRET_POST"
	ClientAuthMethodClientSecretJwt         ClientAuthMethod = "CLIENT_SECRET_JWT"
	ClientAuthMethodPrivateKeyJwt           ClientAuthMethod = "PRIVATE_KEY_JWT"
	ClientAuthMethodTLSClientAuth           ClientAuthMethod = "TLS_CLIENT_AUTH"
	ClientAuthMethodSelfSignedTLSClientAuth ClientAuthMethod = "SELF_SIGNED_TLS_CLIENT_AUTH"
	ClientAuthMethodAttestJwtClientAuth     ClientAuthMethod = "ATTEST_JWT_CLIENT_AUTH"
	ClientAuthMethodSpiffeJwt               ClientAuthMethod = "SPIFFE_JWT"
)

func (e ClientAuthMethod) ToPointer() *ClientAuthMethod {
	return &e
}
func (e *ClientAuthMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NONE":
		fallthrough
	case "CLIENT_SECRET_BASIC":
		fallthrough
	case "CLIENT_SECRET_POST":
		fallthrough
	case "CLIENT_SECRET_JWT":
		fallthrough
	case "PRIVATE_KEY_JWT":
		fallthrough
	case "TLS_CLIENT_AUTH":
		fallthrough
	case "SELF_SIGNED_TLS_CLIENT_AUTH":
		fallthrough
	case "ATTEST_JWT_CLIENT_AUTH":
		fallthrough
	case "SPIFFE_JWT":
		*e = ClientAuthMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ClientAuthMethod: %v", v)
	}
}
