// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ClientSecretRefreshResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The new client secret.
	//
	NewClientSecret *string `json:"newClientSecret,omitzero"`
	// The old client secret.
	//
	OldClientSecret *string `json:"oldClientSecret,omitzero"`
}

func (c *ClientSecretRefreshResponse) GetResultCode() *string {
	if c == nil {
		return nil
	}
	return c.ResultCode
}

func (c *ClientSecretRefreshResponse) GetResultMessage() *string {
	if c == nil {
		return nil
	}
	return c.ResultMessage
}

func (c *ClientSecretRefreshResponse) GetNewClientSecret() *string {
	if c == nil {
		return nil
	}
	return c.NewClientSecret
}

func (c *ClientSecretRefreshResponse) GetOldClientSecret() *string {
	if c == nil {
		return nil
	}
	return c.OldClientSecret
}
