// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ClientAuthorizationUpdateResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
}

func (c *ClientAuthorizationUpdateResponse) GetResultCode() *string {
	if c == nil {
		return nil
	}
	return c.ResultCode
}

func (c *ClientAuthorizationUpdateResponse) GetResultMessage() *string {
	if c == nil {
		return nil
	}
	return c.ResultMessage
}
