// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 733428e4bf94

package shared

type ClientSecretUpdateRequest struct {
	// The new value of the client secret. Valid characters for a client secret are `A-Z`, `a-z`, `0-9`,
	// `-`, and `_`. The maximum length of a client secret is 86.
	//
	ClientSecret string `json:"clientSecret" form:"name=clientSecret"`
}

func (c *ClientSecretUpdateRequest) GetClientSecret() string {
	if c == nil {
		return ""
	}
	return c.ClientSecret
}
