// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: aba92fd618c9

package shared

import (
	"encoding/json"
	"fmt"
)

// ClientRegistrationType - Values for the `client_registration_types` RP metadata and the
//
//	`client_registration_types_supported` OP metadata that are defined in
//	[OpenID Connect Federation 1.0](https://openid.net/specs/openid-connect-federation-1_0.html).
type ClientRegistrationType string

const (
	ClientRegistrationTypeAutomatic ClientRegistrationType = "AUTOMATIC"
	ClientRegistrationTypeExplicit  ClientRegistrationType = "EXPLICIT"
)

func (e ClientRegistrationType) ToPointer() *ClientRegistrationType {
	return &e
}
func (e *ClientRegistrationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AUTOMATIC":
		fallthrough
	case "EXPLICIT":
		*e = ClientRegistrationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ClientRegistrationType: %v", v)
	}
}
