// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ClientAuthorizationGetListRequest struct {
	// Unique user ID of an end-user.
	Subject string `json:"subject" form:"name=subject"`
	// Unique ID of a client developer.
	Developer *string `json:"developer,omitzero" form:"name=developer"`
	// Start index of search results (inclusive).
	Start *int `json:"start,omitzero" form:"name=start"`
	// End index of search results (exclusive).
	End *int `json:"end,omitzero" form:"name=end"`
}

func (c *ClientAuthorizationGetListRequest) GetSubject() string {
	if c == nil {
		return ""
	}
	return c.Subject
}

func (c *ClientAuthorizationGetListRequest) GetDeveloper() *string {
	if c == nil {
		return nil
	}
	return c.Developer
}

func (c *ClientAuthorizationGetListRequest) GetStart() *int {
	if c == nil {
		return nil
	}
	return c.Start
}

func (c *ClientAuthorizationGetListRequest) GetEnd() *int {
	if c == nil {
		return nil
	}
	return c.End
}
