// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
)

type CredentialIssuerMetadata struct {
	// The identifiers of the authorization servers that the credential issuer relies on for authorization.
	// This property corresponds to the authorization_servers metadata. When the credential issuer works
	// as an authorization server for itself, this property should be omitted.
	//
	AuthorizationServers []string `json:"authorizationServers,omitzero"`
	// The identifier of a credential request.
	CredentialIssuer *string `json:"credentialIssuer,omitzero"`
	// The URL of the credential endpoint of the credential issuer.
	CredentialEndpoint *string `json:"credentialEndpoint,omitzero"`
	// The URL of the batch credential endpoint of the credential issuer.
	BatchCredentialEndpoint *string `json:"batchCredentialEndpoint,omitzero"`
	// The URL of the deferred credential endpoint of the credential issuer.
	DeferredCredentialEndpoint *string `json:"deferredCredentialEndpoint,omitzero"`
	// A JSON object describing supported credential configurations.
	// This property corresponds to the credential_configurations_supported metadata.
	// Note: Due to a breaking change in December 2023, this was changed from a JSON array to a JSON object.
	//
	CredentialsSupported *string `json:"credentialsSupported,omitzero"`
	// The supported JWE `alg` algorithms for credential response encryption. This property corresponds
	// to the `credential_response_encryption.alg_values_supported` metadata.
	//
	CredentialResponseEncryptionAlgValuesSupported []string `json:"credentialResponseEncryptionAlgValuesSupported,omitzero"`
	// The supported JWE `enc` algorithms for credential response encryption. This property corresponds
	// to the `credential_response_encryption.enc_values_supported` metadata.
	//
	CredentialResponseEncryptionEncValuesSupported []string `json:"credentialResponseEncryptionEncValuesSupported,omitzero"`
	// The boolean flag indicating whether credential response encryption is required. This property
	// corresponds to the `credential_response_encryption.encryption_required metadata`. If this flag
	// is `true`, every credential request to the credential issuer must include the `credential_response_encryption`
	// property.
	//
	RequireCredentialResponseEncryption *bool `json:"requireCredentialResponseEncryption,omitzero"`
	// The boolean flag indicating whether credential request encryption is required. This property
	// corresponds to the `credential_request_encryption.encryption_required` metadata. If this flag
	// is `true`, every credential request to the credential issuer must be encrypted.
	//
	RequireCredentialRequestEncryption *bool `json:"requireCredentialRequestEncryption,omitzero"`
	// The supported JWE `zip` (compression) algorithms for credential response encryption. This
	// property corresponds to the `credential_response_encryption.zip_values_supported` metadata.
	//
	CredentialResponseEncryptionZipValuesSupported []string `json:"credentialResponseEncryptionZipValuesSupported,omitzero"`
	// The maximum array size for the `proofs` parameter in a credential request. This property
	// corresponds to the `batch_credential_issuance.batch_size` metadata. If the value of this
	// property is 2 or greater, the `batch_credential_issuance` parameter will appear in the
	// response from the credential issuer metadata endpoint.
	//
	BatchSize *int64 `json:"batchSize,omitzero"`
}

func (c CredentialIssuerMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CredentialIssuerMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CredentialIssuerMetadata) GetAuthorizationServers() []string {
	if c == nil {
		return nil
	}
	return c.AuthorizationServers
}

func (c *CredentialIssuerMetadata) GetCredentialIssuer() *string {
	if c == nil {
		return nil
	}
	return c.CredentialIssuer
}

func (c *CredentialIssuerMetadata) GetCredentialEndpoint() *string {
	if c == nil {
		return nil
	}
	return c.CredentialEndpoint
}

func (c *CredentialIssuerMetadata) GetBatchCredentialEndpoint() *string {
	if c == nil {
		return nil
	}
	return c.BatchCredentialEndpoint
}

func (c *CredentialIssuerMetadata) GetDeferredCredentialEndpoint() *string {
	if c == nil {
		return nil
	}
	return c.DeferredCredentialEndpoint
}

func (c *CredentialIssuerMetadata) GetCredentialsSupported() *string {
	if c == nil {
		return nil
	}
	return c.CredentialsSupported
}

func (c *CredentialIssuerMetadata) GetCredentialResponseEncryptionAlgValuesSupported() []string {
	if c == nil {
		return nil
	}
	return c.CredentialResponseEncryptionAlgValuesSupported
}

func (c *CredentialIssuerMetadata) GetCredentialResponseEncryptionEncValuesSupported() []string {
	if c == nil {
		return nil
	}
	return c.CredentialResponseEncryptionEncValuesSupported
}

func (c *CredentialIssuerMetadata) GetRequireCredentialResponseEncryption() *bool {
	if c == nil {
		return nil
	}
	return c.RequireCredentialResponseEncryption
}

func (c *CredentialIssuerMetadata) GetRequireCredentialRequestEncryption() *bool {
	if c == nil {
		return nil
	}
	return c.RequireCredentialRequestEncryption
}

func (c *CredentialIssuerMetadata) GetCredentialResponseEncryptionZipValuesSupported() []string {
	if c == nil {
		return nil
	}
	return c.CredentialResponseEncryptionZipValuesSupported
}

func (c *CredentialIssuerMetadata) GetBatchSize() *int64 {
	if c == nil {
		return nil
	}
	return c.BatchSize
}
