// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6f1c5a9f5dc2

package shared

type DeviceVerificationRequest struct {
	// A user code.
	//
	UserCode string `json:"userCode" form:"name=userCode"`
}

func (d *DeviceVerificationRequest) GetUserCode() string {
	if d == nil {
		return ""
	}
	return d.UserCode
}
