// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
)

// DeviceVerificationResponseAction - The next action that the authorization server implementation should take.
type DeviceVerificationResponseAction string

const (
	DeviceVerificationResponseActionInternalServerError DeviceVerificationResponseAction = "INTERNAL_SERVER_ERROR"
	DeviceVerificationResponseActionNotExist            DeviceVerificationResponseAction = "NOT_EXIST"
	DeviceVerificationResponseActionExpired             DeviceVerificationResponseAction = "EXPIRED"
	DeviceVerificationResponseActionValid               DeviceVerificationResponseAction = "VALID"
)

func (e DeviceVerificationResponseAction) ToPointer() *DeviceVerificationResponseAction {
	return &e
}
func (e *DeviceVerificationResponseAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "INTERNAL_SERVER_ERROR":
		fallthrough
	case "NOT_EXIST":
		fallthrough
	case "EXPIRED":
		fallthrough
	case "VALID":
		*e = DeviceVerificationResponseAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeviceVerificationResponseAction: %v", v)
	}
}

type DeviceVerificationResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the authorization server implementation should take.
	Action *DeviceVerificationResponseAction `json:"action,omitzero"`
	// The client ID of the client application to which the user code has been issued.
	//
	ClientID *int64 `json:"clientId,omitzero"`
	// The client ID alias of the client application to which the user code has been issued.
	//
	ClientIDAlias *string `json:"clientIdAlias,omitzero"`
	// `true` if the value of the `client_id` request parameter included in the device authorization
	// request is the client ID alias. `false` if the value is the original numeric client ID.
	//
	ClientIDAliasUsed *bool `json:"clientIdAliasUsed,omitzero"`
	// The name of the client application to which the user code has been issued.
	//
	ClientName *string `json:"clientName,omitzero"`
	// The scopes requested by the device authorization request.
	//
	// Note that `description` property and `descriptions` property of each scope object in
	// the array contained in this property is always null even if descriptions of the scopes
	// are registered.
	//
	Scopes []Scope `json:"scopes,omitzero"`
	// The names of the claims which were requested indirectly via some special scopes.
	// See [5.4. Requesting Claims using Scope Values](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims)
	// in OpenID Connect Core 1.0 for details.
	//
	// This property is always `null` if the `scope` request parameter of the device authorization
	// request does not include the `openid` scope even if special scopes (such as `profile`)
	// are included in the request (unless the openid scope is included in the default set
	// of scopes which is used when the `scope` request parameter is omitted).
	//
	ClaimNames []string `json:"claimNames,omitzero"`
	// The list of ACR values requested by the device authorization request.
	//
	Acrs []string `json:"acrs,omitzero"`
	// The resources specified by the `resource` request parameters or by the `resource` property
	// in the request object. If both are given, the values in the request object should be
	// set. See "Resource Indicators for OAuth 2.0" for details.
	//
	Resources []string `json:"resources,omitzero"`
	// The authorization details. This represents the value of the `authorization_details`
	// request parameter in the preceding device authorization request which is defined in
	// "OAuth 2.0 Rich Authorization Requests".
	//
	AuthorizationDetails *AuthzDetails `json:"authorizationDetails,omitzero"`
	// The attributes of this service that the client application belongs to.
	//
	ServiceAttributes []Pair `json:"serviceAttributes,omitzero"`
	// The attributes of the client.
	//
	ClientAttributes []Pair `json:"clientAttributes,omitzero"`
	// The dynamic scopes which the client application requested by the scope request parameter.
	//
	DynamicScopes []DynamicScope `json:"dynamicScopes,omitzero"`
	// Get the date in milliseconds since the Unix epoch (1970-01-01) at which the user code will expire.
	//
	ExpiresAt *int64 `json:"expiresAt,omitzero"`
	// The grant management action of the device authorization request.
	//
	// The `grant_management_action` request parameter is defined in
	// [Grant Management for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html).
	//
	GmAction *GrantManagementAction `json:"gmAction,omitzero"`
	// the value of the `grant_id` request parameter of the device authorization request.
	//
	// The `grant_id` request parameter is defined in
	// [Grant Management for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html)
	// , which is supported by Authlete 2.3 and newer versions.
	//
	GrantID *string `json:"grantId,omitzero"`
	Grant   *Grant  `json:"grant,omitzero"`
	// The subject identifying the user who has given the grant identified
	// by the `grant_id` request parameter of the device authorization
	// request.
	// Authlete 2.3 and newer versions support [Grant Management
	// for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html). An authorization request may contain a `grant_id`
	// request parameter which is defined in the specification. If the value of
	// the request parameter is valid, &#123;@link #getGrantSubject()&#125; will return
	// the subject of the user who has given the grant to the client application.
	// Authorization server implementations may use the value returned from
	// &#123;@link #getGrantSubject()&#125; in order to determine the user to authenticate.
	// The user your system will authenticate during the authorization process
	// (or has already authenticated) may be different from the user of the
	// grant. The first implementer's draft of "Grant Management for OAuth 2.0"
	// does not mention anything about the case, so the behavior in the case is
	// left to implementations. Authlete will not perform the grant management
	// action when the `subject` passed to Authlete does not match the
	// user of the grant.
	//
	GrantSubject *string `json:"grantSubject,omitzero"`
	// The entity ID of the client.
	//
	ClientEntityID *string `json:"clientEntityId,omitzero"`
	// Flag which indicates whether the entity ID of the client was used when the request for the access token was made.
	//
	ClientEntityIDUsed *bool `json:"clientEntityIdUsed,omitzero"`
	// The location of the client's metadata document that was used to resolve client metadata.
	//
	// This property is set when client metadata was retrieved via the [OAuth Client ID Metadata Document](https://datatracker.ietf.org/doc/draft-ietf-oauth-client-id-metadata-document/) (CIMD) mechanism.
	//
	MetadataDocumentLocation *string `json:"metadataDocumentLocation,omitzero"`
	// Flag indicating whether a metadata document was used to resolve client metadata for this request.
	//
	// When `true`, the client metadata was retrieved via the CIMD mechanism rather than from the Authlete database.
	//
	MetadataDocumentUsed *bool `json:"metadataDocumentUsed,omitzero"`
}

func (d DeviceVerificationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeviceVerificationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeviceVerificationResponse) GetResultCode() *string {
	if d == nil {
		return nil
	}
	return d.ResultCode
}

func (d *DeviceVerificationResponse) GetResultMessage() *string {
	if d == nil {
		return nil
	}
	return d.ResultMessage
}

func (d *DeviceVerificationResponse) GetAction() *DeviceVerificationResponseAction {
	if d == nil {
		return nil
	}
	return d.Action
}

func (d *DeviceVerificationResponse) GetClientID() *int64 {
	if d == nil {
		return nil
	}
	return d.ClientID
}

func (d *DeviceVerificationResponse) GetClientIDAlias() *string {
	if d == nil {
		return nil
	}
	return d.ClientIDAlias
}

func (d *DeviceVerificationResponse) GetClientIDAliasUsed() *bool {
	if d == nil {
		return nil
	}
	return d.ClientIDAliasUsed
}

func (d *DeviceVerificationResponse) GetClientName() *string {
	if d == nil {
		return nil
	}
	return d.ClientName
}

func (d *DeviceVerificationResponse) GetScopes() []Scope {
	if d == nil {
		return nil
	}
	return d.Scopes
}

func (d *DeviceVerificationResponse) GetClaimNames() []string {
	if d == nil {
		return nil
	}
	return d.ClaimNames
}

func (d *DeviceVerificationResponse) GetAcrs() []string {
	if d == nil {
		return nil
	}
	return d.Acrs
}

func (d *DeviceVerificationResponse) GetResources() []string {
	if d == nil {
		return nil
	}
	return d.Resources
}

func (d *DeviceVerificationResponse) GetAuthorizationDetails() *AuthzDetails {
	if d == nil {
		return nil
	}
	return d.AuthorizationDetails
}

func (d *DeviceVerificationResponse) GetServiceAttributes() []Pair {
	if d == nil {
		return nil
	}
	return d.ServiceAttributes
}

func (d *DeviceVerificationResponse) GetClientAttributes() []Pair {
	if d == nil {
		return nil
	}
	return d.ClientAttributes
}

func (d *DeviceVerificationResponse) GetDynamicScopes() []DynamicScope {
	if d == nil {
		return nil
	}
	return d.DynamicScopes
}

func (d *DeviceVerificationResponse) GetExpiresAt() *int64 {
	if d == nil {
		return nil
	}
	return d.ExpiresAt
}

func (d *DeviceVerificationResponse) GetGmAction() *GrantManagementAction {
	if d == nil {
		return nil
	}
	return d.GmAction
}

func (d *DeviceVerificationResponse) GetGrantID() *string {
	if d == nil {
		return nil
	}
	return d.GrantID
}

func (d *DeviceVerificationResponse) GetGrant() *Grant {
	if d == nil {
		return nil
	}
	return d.Grant
}

func (d *DeviceVerificationResponse) GetGrantSubject() *string {
	if d == nil {
		return nil
	}
	return d.GrantSubject
}

func (d *DeviceVerificationResponse) GetClientEntityID() *string {
	if d == nil {
		return nil
	}
	return d.ClientEntityID
}

func (d *DeviceVerificationResponse) GetClientEntityIDUsed() *bool {
	if d == nil {
		return nil
	}
	return d.ClientEntityIDUsed
}

func (d *DeviceVerificationResponse) GetMetadataDocumentLocation() *string {
	if d == nil {
		return nil
	}
	return d.MetadataDocumentLocation
}

func (d *DeviceVerificationResponse) GetMetadataDocumentUsed() *bool {
	if d == nil {
		return nil
	}
	return d.MetadataDocumentUsed
}
