// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9941b458f69f

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
)

// FederationRegistrationResponseAction - The next action that the authorization server implementation should take.
type FederationRegistrationResponseAction string

const (
	FederationRegistrationResponseActionOk                  FederationRegistrationResponseAction = "OK"
	FederationRegistrationResponseActionBadRequest          FederationRegistrationResponseAction = "BAD_REQUEST"
	FederationRegistrationResponseActionNotFound            FederationRegistrationResponseAction = "NOT_FOUND"
	FederationRegistrationResponseActionInternalServerError FederationRegistrationResponseAction = "INTERNAL_SERVER_ERROR"
)

func (e FederationRegistrationResponseAction) ToPointer() *FederationRegistrationResponseAction {
	return &e
}
func (e *FederationRegistrationResponseAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OK":
		fallthrough
	case "BAD_REQUEST":
		fallthrough
	case "NOT_FOUND":
		fallthrough
	case "INTERNAL_SERVER_ERROR":
		*e = FederationRegistrationResponseAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FederationRegistrationResponseAction: %v", v)
	}
}

type FederationRegistrationResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the authorization server implementation should take.
	Action *FederationRegistrationResponseAction `json:"action,omitzero"`
	// The content that the authorization server implementation can use as the value of `WWW-Authenticate`
	// header on errors.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
	Client          *Client `json:"client,omitzero"`
}

func (f FederationRegistrationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FederationRegistrationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FederationRegistrationResponse) GetResultCode() *string {
	if f == nil {
		return nil
	}
	return f.ResultCode
}

func (f *FederationRegistrationResponse) GetResultMessage() *string {
	if f == nil {
		return nil
	}
	return f.ResultMessage
}

func (f *FederationRegistrationResponse) GetAction() *FederationRegistrationResponseAction {
	if f == nil {
		return nil
	}
	return f.Action
}

func (f *FederationRegistrationResponse) GetResponseContent() *string {
	if f == nil {
		return nil
	}
	return f.ResponseContent
}

func (f *FederationRegistrationResponse) GetClient() *Client {
	if f == nil {
		return nil
	}
	return f.Client
}
