// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// GrantManagementAction - The grant management action of the device authorization request.
//
// The `grant_management_action` request parameter is defined in
// [Grant Management for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html).
type GrantManagementAction string

const (
	GrantManagementActionCreate  GrantManagementAction = "CREATE"
	GrantManagementActionQuery   GrantManagementAction = "QUERY"
	GrantManagementActionReplace GrantManagementAction = "REPLACE"
	GrantManagementActionRevoke  GrantManagementAction = "REVOKE"
	GrantManagementActionMerge   GrantManagementAction = "MERGE"
)

func (e GrantManagementAction) ToPointer() *GrantManagementAction {
	return &e
}
func (e *GrantManagementAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CREATE":
		fallthrough
	case "QUERY":
		fallthrough
	case "REPLACE":
		fallthrough
	case "REVOKE":
		fallthrough
	case "MERGE":
		*e = GrantManagementAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GrantManagementAction: %v", v)
	}
}
