// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/authlete/terraform-provider-authlete/internal/sdk/internal/utils"
)

type Grant struct {
	Scopes []GrantScope `json:"scopes,omitzero"`
	// The claims associated with the Grant.
	//
	Claims []string `json:"claims,omitzero"`
	// The authorization details. This represents the value of the `authorization_details`
	// request parameter in the preceding device authorization request which is defined in
	// "OAuth 2.0 Rich Authorization Requests".
	//
	AuthorizationDetails *AuthzDetails `json:"authorizationDetails,omitzero"`
}

func (g Grant) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *Grant) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *Grant) GetScopes() []GrantScope {
	if g == nil {
		return nil
	}
	return g.Scopes
}

func (g *Grant) GetClaims() []string {
	if g == nil {
		return nil
	}
	return g.Claims
}

func (g *Grant) GetAuthorizationDetails() *AuthzDetails {
	if g == nil {
		return nil
	}
	return g.AuthorizationDetails
}
