// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1838a349dc68

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
)

// HskGetResponseAction - Result of the API call
type HskGetResponseAction string

const (
	HskGetResponseActionSuccess        HskGetResponseAction = "SUCCESS"
	HskGetResponseActionInvalidRequest HskGetResponseAction = "INVALID_REQUEST"
	HskGetResponseActionNotFound       HskGetResponseAction = "NOT_FOUND"
	HskGetResponseActionServerError    HskGetResponseAction = "SERVER_ERROR"
)

func (e HskGetResponseAction) ToPointer() *HskGetResponseAction {
	return &e
}
func (e *HskGetResponseAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SUCCESS":
		fallthrough
	case "INVALID_REQUEST":
		fallthrough
	case "NOT_FOUND":
		fallthrough
	case "SERVER_ERROR":
		*e = HskGetResponseAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for HskGetResponseAction: %v", v)
	}
}

type HskGetResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// Result of the API call
	Action *HskGetResponseAction `json:"action,omitzero"`
	// Holds information about a key managed in an HSM (Hardware Security Module)
	//
	Hsk *Hsk `json:"hsk,omitzero"`
}

func (h HskGetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HskGetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HskGetResponse) GetResultCode() *string {
	if h == nil {
		return nil
	}
	return h.ResultCode
}

func (h *HskGetResponse) GetResultMessage() *string {
	if h == nil {
		return nil
	}
	return h.ResultMessage
}

func (h *HskGetResponse) GetAction() *HskGetResponseAction {
	if h == nil {
		return nil
	}
	return h.Action
}

func (h *HskGetResponse) GetHsk() *Hsk {
	if h == nil {
		return nil
	}
	return h.Hsk
}
