// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
)

// IdpError - Error response returned by the Authlete IdP server. Unlike the main API's
// `resultCode`/`resultMessage` format, IdP errors carry a human-readable `error` message,
// optionally accompanied by contextual fields (such as `organizationId` or `apiServerId`).
// Request validation failures instead return an `errors` array of per-field messages.
type IdpError struct {
	// A human-readable error message.
	Error *string `json:"error,omitzero"`
	// Per-field validation error messages, present for request validation failures.
	Errors               []string `json:"errors,omitzero"`
	AdditionalProperties any      `additionalProperties:"true" json:"-"`
}

func (i IdpError) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IdpError) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IdpError) GetError() *string {
	if i == nil {
		return nil
	}
	return i.Error
}

func (i *IdpError) GetErrors() []string {
	if i == nil {
		return nil
	}
	return i.Errors
}

func (i *IdpError) GetAdditionalProperties() any {
	if i == nil {
		return nil
	}
	return i.AdditionalProperties
}
