// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ab8ad0e2fe72

package shared

import (
	"encoding/json"
	"fmt"
)

// JweAlg - this is the 'alg' header value for encrypted JWT tokens.
// Depending upon the context, this refers to key transport scheme to be used by the client and by the server. For instance:
// - as `authorizationEncryptionAlg` value, it refers to the encoding algorithm used by server for transporting they keys on JARM objects
// - as `requestEncryptionAlg` value, it refers to the expected key transport encoding algorithm that server expect from client when encrypting a Request Object
// - as `idTokenEncryptionAlg` value, it refers to the algorithm used by the server to key transport of id_tokens
//
// **Please note that some of the algorithms are more secure than others, some are not supported very well cross platforms and some (like RSA1_5) is known to be weak**.
type JweAlg string

const (
	JweAlgRsa15            JweAlg = "RSA1_5"
	JweAlgRsaOaep          JweAlg = "RSA_OAEP"
	JweAlgRsaOaep256       JweAlg = "RSA_OAEP_256"
	JweAlgA128Kw           JweAlg = "A128KW"
	JweAlgA192Kw           JweAlg = "A192KW"
	JweAlgA256Kw           JweAlg = "A256KW"
	JweAlgDir              JweAlg = "DIR"
	JweAlgEcdhEs           JweAlg = "ECDH_ES"
	JweAlgEcdhEsA128Kw     JweAlg = "ECDH_ES_A128KW"
	JweAlgEcdhEsA192Kw     JweAlg = "ECDH_ES_A192KW"
	JweAlgEcdhEsA256Kw     JweAlg = "ECDH_ES_A256KW"
	JweAlgA128Gcmkw        JweAlg = "A128GCMKW"
	JweAlgA192Gcmkw        JweAlg = "A192GCMKW"
	JweAlgA256Gcmkw        JweAlg = "A256GCMKW"
	JweAlgPbes2Hs256A128Kw JweAlg = "PBES2_HS256_A128KW"
	JweAlgPbes2Hs384A192Kw JweAlg = "PBES2_HS384_A192KW"
	JweAlgPbes2Hs512A256Kw JweAlg = "PBES2_HS512_A256KW"
)

func (e JweAlg) ToPointer() *JweAlg {
	return &e
}
func (e *JweAlg) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "RSA1_5":
		fallthrough
	case "RSA_OAEP":
		fallthrough
	case "RSA_OAEP_256":
		fallthrough
	case "A128KW":
		fallthrough
	case "A192KW":
		fallthrough
	case "A256KW":
		fallthrough
	case "DIR":
		fallthrough
	case "ECDH_ES":
		fallthrough
	case "ECDH_ES_A128KW":
		fallthrough
	case "ECDH_ES_A192KW":
		fallthrough
	case "ECDH_ES_A256KW":
		fallthrough
	case "A128GCMKW":
		fallthrough
	case "A192GCMKW":
		fallthrough
	case "A256GCMKW":
		fallthrough
	case "PBES2_HS256_A128KW":
		fallthrough
	case "PBES2_HS384_A192KW":
		fallthrough
	case "PBES2_HS512_A256KW":
		*e = JweAlg(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JweAlg: %v", v)
	}
}
