// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d6fb5d628437

package shared

import (
	"encoding/json"
	"fmt"
)

// JwsAlg - The signature algorithm for JWT. This value is represented on 'alg' attribute
// of the header of JWT.
//
// it's semantics depends upon where is this defined, for instance:
//   - as service accessTokenSignAlg value, it defines that access token are JWT and the algorithm used to sign it. Check your [KB article](https://kb.authlete.com/en/s/oauth-and-openid-connect/a/jwt-based-access-token).
//   - as client authorizationSignAlg value, it represents the signature algorithm used when [creating a JARM response](https://kb.authlete.com/en/s/oauth-and-openid-connect/a/enabling-jarm).
//   - or as client requestSignAlg value, it specifies which is the expected signature used by [client on a Request Object](https://kb.authlete.com/en/s/oauth-and-openid-connect/a/request-objects).
type JwsAlg string

const (
	JwsAlgNone   JwsAlg = "NONE"
	JwsAlgHs256  JwsAlg = "HS256"
	JwsAlgHs384  JwsAlg = "HS384"
	JwsAlgHs512  JwsAlg = "HS512"
	JwsAlgRs256  JwsAlg = "RS256"
	JwsAlgRs384  JwsAlg = "RS384"
	JwsAlgRs512  JwsAlg = "RS512"
	JwsAlgEs256  JwsAlg = "ES256"
	JwsAlgEs384  JwsAlg = "ES384"
	JwsAlgEs512  JwsAlg = "ES512"
	JwsAlgPs256  JwsAlg = "PS256"
	JwsAlgPs384  JwsAlg = "PS384"
	JwsAlgPs512  JwsAlg = "PS512"
	JwsAlgEs256K JwsAlg = "ES256K"
	JwsAlgEdDsa  JwsAlg = "EdDSA"
)

func (e JwsAlg) ToPointer() *JwsAlg {
	return &e
}
func (e *JwsAlg) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NONE":
		fallthrough
	case "HS256":
		fallthrough
	case "HS384":
		fallthrough
	case "HS512":
		fallthrough
	case "RS256":
		fallthrough
	case "RS384":
		fallthrough
	case "RS512":
		fallthrough
	case "ES256":
		fallthrough
	case "ES384":
		fallthrough
	case "ES512":
		fallthrough
	case "PS256":
		fallthrough
	case "PS384":
		fallthrough
	case "PS512":
		fallthrough
	case "ES256K":
		fallthrough
	case "EdDSA":
		*e = JwsAlg(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JwsAlg: %v", v)
	}
}
