// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NamedURI struct {
	Name *string `json:"name,omitzero"`
	URI  *string `json:"uri,omitzero"`
}

func (n *NamedURI) GetName() *string {
	if n == nil {
		return nil
	}
	return n.Name
}

func (n *NamedURI) GetURI() *string {
	if n == nil {
		return nil
	}
	return n.URI
}
