// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NativeSsoLogoutRequest struct {
	// The session ID of a user's authentication session.
	//
	SessionID string `json:"sessionId"`
}

func (n *NativeSsoLogoutRequest) GetSessionID() string {
	if n == nil {
		return ""
	}
	return n.SessionID
}
