// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 97e359a43bd7

package shared

type Pair struct {
	// The key part.
	Key *string `json:"key,omitzero"`
	// The value part.
	Value *string `json:"value,omitzero"`
}

func (p *Pair) GetKey() *string {
	if p == nil {
		return nil
	}
	return p.Key
}

func (p *Pair) GetValue() *string {
	if p == nil {
		return nil
	}
	return p.Value
}
