// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 21294e42e7f8

package shared

import (
	"encoding/json"
	"fmt"
)

// Prompt - The prompt that the UI displayed to the end-user must satisfy as the minimum level. This value comes from `prompt` request parameter.
//
// When the authorization request does not contain `prompt` request parameter, `CONSENT` is used as the default value.
//
// See "[OpenID Connect Core 1.0, 3.1.2.1. Authentication Request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest), prompt" for `prompt` request parameter.
type Prompt string

const (
	PromptNone          Prompt = "NONE"
	PromptLogin         Prompt = "LOGIN"
	PromptConsent       Prompt = "CONSENT"
	PromptSelectAccount Prompt = "SELECT_ACCOUNT"
	PromptCreate        Prompt = "CREATE"
)

func (e Prompt) ToPointer() *Prompt {
	return &e
}
func (e *Prompt) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NONE":
		fallthrough
	case "LOGIN":
		fallthrough
	case "CONSENT":
		fallthrough
	case "SELECT_ACCOUNT":
		fallthrough
	case "CREATE":
		*e = Prompt(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Prompt: %v", v)
	}
}
