// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6f28ae3d7f00

package shared

import (
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
)

type PushedAuthorizationRequest struct {
	// The pushed authorization request body received from the client application.
	//
	// The value of parameters is the entire entity body (which is formatted in `application/x-www-form-urlencoded`) of the request from
	// the client application.
	//
	Parameters string `json:"parameters" form:"name=parameters"`
	// The client ID extracted from `Authorization` header of the pushed request from the client application.
	//
	ClientID *string `json:"clientId,omitzero" form:"name=clientId"`
	// The client secret extracted from `Authorization` header of the pushed authorization request from the client application.
	//
	ClientSecret *string `json:"clientSecret,omitzero" form:"name=clientSecret"`
	// The client certificate from the MTLS connection to pushed authorization endpoint from the client application.
	ClientCertificate *string `json:"clientCertificate,omitzero" form:"name=clientCertificate"`
	// The certificate path presented by the client during client authentication. These certificates are strings in PEM format.
	//
	ClientCertificatePath []string `json:"clientCertificatePath,omitzero" form:"name=clientCertificatePath"`
	// DPoP Header
	//
	Dpop *string `json:"dpop,omitzero" form:"name=dpop"`
	// HTTP Method (for DPoP validation).
	//
	Htm *string `json:"htm,omitzero" form:"name=htm"`
	// HTTP URL base (for DPoP validation).
	//
	Htu *string `json:"htu,omitzero" form:"name=htu"`
	// The value of the `OAuth-Client-Attestation` HTTP header, which is defined in the specification
	// of [OAuth 2.0 Attestation-Based Client Authentication](https://datatracker.ietf.org/doc/draft-ietf-oauth-attestation-based-client-auth/).
	//
	OauthClientAttestation *string `json:"oauthClientAttestation,omitzero" form:"name=oauthClientAttestation"`
	// The value of the `OAuth-Client-Attestation-PoP` HTTP header, which is defined in the specification
	// of [OAuth 2.0 Attestation-Based Client Authentication](https://datatracker.ietf.org/doc/draft-ietf-oauth-attestation-based-client-auth/).
	//
	OauthClientAttestationPop *string `json:"oauthClientAttestationPop,omitzero" form:"name=oauthClientAttestationPop"`
	// The flag indicating whether to require the DPoP proof JWT to include the `nonce` claim. Even if
	// the service's `dpopNonceRequired` property is `false`, calling the `/pushed_auth_req` API with
	// this `dpopNonceRequired` parameter `true` will force the Authlete API to check whether the DPoP
	// proof JWT includes the expected `nonce` value.
	//
	DpopNonceRequired *bool `json:"dpopNonceRequired,omitzero" form:"name=dpopNonceRequired"`
}

func (p PushedAuthorizationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PushedAuthorizationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PushedAuthorizationRequest) GetParameters() string {
	if p == nil {
		return ""
	}
	return p.Parameters
}

func (p *PushedAuthorizationRequest) GetClientID() *string {
	if p == nil {
		return nil
	}
	return p.ClientID
}

func (p *PushedAuthorizationRequest) GetClientSecret() *string {
	if p == nil {
		return nil
	}
	return p.ClientSecret
}

func (p *PushedAuthorizationRequest) GetClientCertificate() *string {
	if p == nil {
		return nil
	}
	return p.ClientCertificate
}

func (p *PushedAuthorizationRequest) GetClientCertificatePath() []string {
	if p == nil {
		return nil
	}
	return p.ClientCertificatePath
}

func (p *PushedAuthorizationRequest) GetDpop() *string {
	if p == nil {
		return nil
	}
	return p.Dpop
}

func (p *PushedAuthorizationRequest) GetHtm() *string {
	if p == nil {
		return nil
	}
	return p.Htm
}

func (p *PushedAuthorizationRequest) GetHtu() *string {
	if p == nil {
		return nil
	}
	return p.Htu
}

func (p *PushedAuthorizationRequest) GetOauthClientAttestation() *string {
	if p == nil {
		return nil
	}
	return p.OauthClientAttestation
}

func (p *PushedAuthorizationRequest) GetOauthClientAttestationPop() *string {
	if p == nil {
		return nil
	}
	return p.OauthClientAttestationPop
}

func (p *PushedAuthorizationRequest) GetDpopNonceRequired() *bool {
	if p == nil {
		return nil
	}
	return p.DpopNonceRequired
}
