// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ResponseType string

const (
	ResponseTypeNone             ResponseType = "NONE"
	ResponseTypeCode             ResponseType = "CODE"
	ResponseTypeToken            ResponseType = "TOKEN"
	ResponseTypeIDToken          ResponseType = "ID_TOKEN"
	ResponseTypeCodeToken        ResponseType = "CODE_TOKEN"
	ResponseTypeCodeIDToken      ResponseType = "CODE_ID_TOKEN"
	ResponseTypeIDTokenToken     ResponseType = "ID_TOKEN_TOKEN"
	ResponseTypeCodeIDTokenToken ResponseType = "CODE_ID_TOKEN_TOKEN"
)

func (e ResponseType) ToPointer() *ResponseType {
	return &e
}
func (e *ResponseType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NONE":
		fallthrough
	case "CODE":
		fallthrough
	case "TOKEN":
		fallthrough
	case "ID_TOKEN":
		fallthrough
	case "CODE_TOKEN":
		fallthrough
	case "CODE_ID_TOKEN":
		fallthrough
	case "ID_TOKEN_TOKEN":
		fallthrough
	case "CODE_ID_TOKEN_TOKEN":
		*e = ResponseType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ResponseType: %v", v)
	}
}
