// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8eff0f25421f

package shared

import (
	"encoding/json"
	"fmt"
)

// RevocationResponseAction - The next action that the authorization server implementation should take.
type RevocationResponseAction string

const (
	RevocationResponseActionInternalServerError RevocationResponseAction = "INTERNAL_SERVER_ERROR"
	RevocationResponseActionInvalidClient       RevocationResponseAction = "INVALID_CLIENT"
	RevocationResponseActionBadRequest          RevocationResponseAction = "BAD_REQUEST"
	RevocationResponseActionOk                  RevocationResponseAction = "OK"
)

func (e RevocationResponseAction) ToPointer() *RevocationResponseAction {
	return &e
}
func (e *RevocationResponseAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "INTERNAL_SERVER_ERROR":
		fallthrough
	case "INVALID_CLIENT":
		fallthrough
	case "BAD_REQUEST":
		fallthrough
	case "OK":
		*e = RevocationResponseAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RevocationResponseAction: %v", v)
	}
}

type RevocationResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the authorization server implementation should take.
	Action *RevocationResponseAction `json:"action,omitzero"`
	// The content that the authorization server implementation is to return to the client application.
	// Its format varies depending on the value of `action` parameter.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
}

func (r *RevocationResponse) GetResultCode() *string {
	if r == nil {
		return nil
	}
	return r.ResultCode
}

func (r *RevocationResponse) GetResultMessage() *string {
	if r == nil {
		return nil
	}
	return r.ResultMessage
}

func (r *RevocationResponse) GetAction() *RevocationResponseAction {
	if r == nil {
		return nil
	}
	return r.Action
}

func (r *RevocationResponse) GetResponseContent() *string {
	if r == nil {
		return nil
	}
	return r.ResponseContent
}
