// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9098af98367e

package shared

type Security struct {
	Bearer *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (s *Security) GetBearer() *string {
	if s == nil {
		return nil
	}
	return s.Bearer
}
