// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ec06c9ac65f8

package shared

import (
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
)

type ServiceGetListResponse struct {
	// Start index (inclusive) of the result set. The default value is 0. Must not be a negative
	// number.
	//
	Start *int `json:"start,omitzero"`
	// Start index (inclusive) of the result set. The default value is 0. Must not be a negative
	// number.
	//
	End *int `json:"end,omitzero"`
	// Total number of services owned by the service owner. This doesn't mean the number of services
	// contained in the response.
	//
	TotalCount *int `json:"totalCount,omitzero"`
	// An array of services.
	//
	Services []Service `json:"services,omitzero"`
}

func (s ServiceGetListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ServiceGetListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *ServiceGetListResponse) GetStart() *int {
	if s == nil {
		return nil
	}
	return s.Start
}

func (s *ServiceGetListResponse) GetEnd() *int {
	if s == nil {
		return nil
	}
	return s.End
}

func (s *ServiceGetListResponse) GetTotalCount() *int {
	if s == nil {
		return nil
	}
	return s.TotalCount
}

func (s *ServiceGetListResponse) GetServices() []Service {
	if s == nil {
		return nil
	}
	return s.Services
}
