// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ServiceProfile string

const (
	ServiceProfileFapi        ServiceProfile = "FAPI"
	ServiceProfileOpenBanking ServiceProfile = "OPEN_BANKING"
)

func (e ServiceProfile) ToPointer() *ServiceProfile {
	return &e
}
func (e *ServiceProfile) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "FAPI":
		fallthrough
	case "OPEN_BANKING":
		*e = ServiceProfile(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ServiceProfile: %v", v)
	}
}
