// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SnsCredentials struct {
	// SNS.
	Sns *string `json:"sns,omitzero"`
	// API key.
	APIKey *string `json:"apiKey,omitzero"`
	// API secret.
	APISecret *string `json:"apiSecret,omitzero"`
}

func (s *SnsCredentials) GetSns() *string {
	if s == nil {
		return nil
	}
	return s.Sns
}

func (s *SnsCredentials) GetAPIKey() *string {
	if s == nil {
		return nil
	}
	return s.APIKey
}

func (s *SnsCredentials) GetAPISecret() *string {
	if s == nil {
		return nil
	}
	return s.APISecret
}
