// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/authlete/terraform-provider-authlete/internal/sdk/internal/utils"
)

// TokenCreateResponseAction - The next action that the authorization server implementation should take.
type TokenCreateResponseAction string

const (
	TokenCreateResponseActionInternalServerError TokenCreateResponseAction = "INTERNAL_SERVER_ERROR"
	TokenCreateResponseActionBadRequest          TokenCreateResponseAction = "BAD_REQUEST"
	TokenCreateResponseActionForbidden           TokenCreateResponseAction = "FORBIDDEN"
	TokenCreateResponseActionOk                  TokenCreateResponseAction = "OK"
)

func (e TokenCreateResponseAction) ToPointer() *TokenCreateResponseAction {
	return &e
}
func (e *TokenCreateResponseAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "INTERNAL_SERVER_ERROR":
		fallthrough
	case "BAD_REQUEST":
		fallthrough
	case "FORBIDDEN":
		fallthrough
	case "OK":
		*e = TokenCreateResponseAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TokenCreateResponseAction: %v", v)
	}
}

type TokenCreateResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the authorization server implementation should take.
	Action *TokenCreateResponseAction `json:"action,omitzero"`
	// The newly issued access token.
	AccessToken *string `json:"accessToken,omitzero"`
	// The ID of the client application associated with the access token.
	//
	ClientID *int64 `json:"clientId,omitzero"`
	// The time at which the access token expires.
	//
	ExpiresAt *int64 `json:"expiresAt,omitzero"`
	// The duration of the newly issued access token in seconds.
	//
	ExpiresIn *int64 `json:"expiresIn,omitzero"`
	// The grant type for the newly issued access token.
	//
	GrantType *string `json:"grantType,omitzero"`
	// The extra properties associated with the access token.
	//
	Properties []Property `json:"properties,omitzero"`
	// The newly issued refresh token.
	//
	RefreshToken *string `json:"refreshToken,omitzero"`
	// Scopes which are associated with the access token.
	//
	Scopes []string `json:"scopes,omitzero"`
	// The subject (= unique identifier) of the user associated with the newly issued access
	// token.
	//
	Subject *string `json:"subject,omitzero"`
	// The token type of the access token.
	//
	TokenType *string `json:"tokenType,omitzero"`
	// If the authorization server is configured to issue JWT-based access tokens (= if `Service.accessTokenSignAlg`
	// is set to a `non-null` value), a JWT-based access token is issued along with the original
	// random-string one.
	//
	JwtAccessToken *string `json:"jwtAccessToken,omitzero"`
	// The authorization details. This represents the value of the `authorization_details`
	// request parameter in the preceding device authorization request which is defined in
	// "OAuth 2.0 Rich Authorization Requests".
	//
	AuthorizationDetails *AuthzDetails `json:"authorizationDetails,omitzero"`
	// the flag which indicates whether the access token is for an external
	// attachment.
	//
	ForExternalAttachment *bool `json:"forExternalAttachment,omitzero"`
	// Set the unique token identifier.
	//
	TokenID *string `json:"tokenId,omitzero"`
	// The scopes associated with the refresh token. May be null.
	//
	RefreshTokenScopes []string `json:"refreshTokenScopes,omitzero"`
	// The client Identifier that will be associated with a newly created access token.
	//
	ClientIdentifier *string `json:"clientIdentifier,omitzero"`
	// The session ID associated with a newly created access token.
	//
	// NOTE: A refresh token must be associated with a session ID, which is the ID of the user's authentication
	// session, in order to be used to obtain a [Native SSO](https://openid.net/specs/openid-connect-native-sso-1_0.html)-compliant
	// ID token in the refresh token flow.
	//
	SessionID *string `json:"sessionId,omitzero"`
}

func (t TokenCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TokenCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TokenCreateResponse) GetResultCode() *string {
	if t == nil {
		return nil
	}
	return t.ResultCode
}

func (t *TokenCreateResponse) GetResultMessage() *string {
	if t == nil {
		return nil
	}
	return t.ResultMessage
}

func (t *TokenCreateResponse) GetAction() *TokenCreateResponseAction {
	if t == nil {
		return nil
	}
	return t.Action
}

func (t *TokenCreateResponse) GetAccessToken() *string {
	if t == nil {
		return nil
	}
	return t.AccessToken
}

func (t *TokenCreateResponse) GetClientID() *int64 {
	if t == nil {
		return nil
	}
	return t.ClientID
}

func (t *TokenCreateResponse) GetExpiresAt() *int64 {
	if t == nil {
		return nil
	}
	return t.ExpiresAt
}

func (t *TokenCreateResponse) GetExpiresIn() *int64 {
	if t == nil {
		return nil
	}
	return t.ExpiresIn
}

func (t *TokenCreateResponse) GetGrantType() *string {
	if t == nil {
		return nil
	}
	return t.GrantType
}

func (t *TokenCreateResponse) GetProperties() []Property {
	if t == nil {
		return nil
	}
	return t.Properties
}

func (t *TokenCreateResponse) GetRefreshToken() *string {
	if t == nil {
		return nil
	}
	return t.RefreshToken
}

func (t *TokenCreateResponse) GetScopes() []string {
	if t == nil {
		return nil
	}
	return t.Scopes
}

func (t *TokenCreateResponse) GetSubject() *string {
	if t == nil {
		return nil
	}
	return t.Subject
}

func (t *TokenCreateResponse) GetTokenType() *string {
	if t == nil {
		return nil
	}
	return t.TokenType
}

func (t *TokenCreateResponse) GetJwtAccessToken() *string {
	if t == nil {
		return nil
	}
	return t.JwtAccessToken
}

func (t *TokenCreateResponse) GetAuthorizationDetails() *AuthzDetails {
	if t == nil {
		return nil
	}
	return t.AuthorizationDetails
}

func (t *TokenCreateResponse) GetForExternalAttachment() *bool {
	if t == nil {
		return nil
	}
	return t.ForExternalAttachment
}

func (t *TokenCreateResponse) GetTokenID() *string {
	if t == nil {
		return nil
	}
	return t.TokenID
}

func (t *TokenCreateResponse) GetRefreshTokenScopes() []string {
	if t == nil {
		return nil
	}
	return t.RefreshTokenScopes
}

func (t *TokenCreateResponse) GetClientIdentifier() *string {
	if t == nil {
		return nil
	}
	return t.ClientIdentifier
}

func (t *TokenCreateResponse) GetSessionID() *string {
	if t == nil {
		return nil
	}
	return t.SessionID
}
