// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f44977cc2dd0

package shared

import (
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
)

type TokenCreateRequest struct {
	// The grant type of the access token when the access token was created.
	//
	GrantType GrantType `json:"grantType" form:"name=grantType"`
	// The ID of the client application which will be associated with a newly created access token.
	//
	ClientID *int64 `json:"clientId,omitzero" form:"name=clientId"`
	// The subject (= unique identifier) of the user who will be associated with a newly created access
	// token. This parameter is required unless the grant type is `CLIENT_CREDENTIALS`. The value must
	// consist of only ASCII characters and its length must not exceed 100.
	//
	Subject *string `json:"subject,omitzero" form:"name=subject"`
	// The scopes which will be associated with a newly created access token. Scopes that are not supported
	// by the service cannot be specified and requesting them will cause an error.
	//
	Scopes []string `json:"scopes,omitzero" form:"name=scopes"`
	// The duration of a newly created access token in seconds. If the value is 0, the duration is determined
	// according to the settings of the service.
	//
	AccessTokenDuration *int64 `json:"accessTokenDuration,omitzero" form:"name=accessTokenDuration"`
	// The duration of a newly created refresh token in seconds. If the value is 0, the duration is
	// determined according to the settings of the service.
	//
	// A refresh token is not created (1) if the service does not support `REFRESH_TOKEN`, or (2) if the
	// specified grant type is either `IMPLICIT`or `CLIENT_CREDENTIALS`.
	//
	RefreshTokenDuration *int64 `json:"refreshTokenDuration,omitzero" form:"name=refreshTokenDuration"`
	// Extra properties to associate with a newly created access token. Note that properties parameter
	// is accepted only when the HTTP method of the request is POST and Content-Type of the request is
	// `application/json`, so don't use `GET` method or `application/x-www-form-urlencoded` if you want
	// to specify properties.
	//
	Properties []Property `json:"properties,omitzero" form:"name=properties,json"`
	// A boolean request parameter which indicates whether to emulate that the client ID alias is used
	// instead of the original numeric client ID when a new access token is created.
	//
	ClientIDAliasUsed *bool `json:"clientIdAliasUsed,omitzero" form:"name=clientIdAliasUsed"`
	// The value of the new access token.
	//
	AccessToken *string `json:"accessToken,omitzero" form:"name=accessToken"`
	// The value of the new refresh token.
	//
	RefreshToken *string `json:"refreshToken,omitzero" form:"name=refreshToken"`
	// Get whether the access token expires or not. By default, all access tokens expire after a period
	// of time determined by their service.
	//
	// If this request parameter is `true`, then the access token will not automatically expire and must
	// be revoked or deleted manually at the service. If this request parameter is true, the `accessTokenDuration`
	// request parameter is ignored.
	//
	AccessTokenPersistent *bool `json:"accessTokenPersistent,omitzero" form:"name=accessTokenPersistent"`
	// The thumbprint of the MTLS certificate bound to this token. If this property is set, a certificate
	// with the corresponding value MUST be presented with the access token when it is used by a client.
	// The value of this property must be a SHA256 certificate thumbprint, base64url encoded.
	//
	CertificateThumbprint *string `json:"certificateThumbprint,omitzero" form:"name=certificateThumbprint"`
	// The thumbprint of the public key used for DPoP presentation of this token. If this property is
	// set, a DPoP proof signed with the corresponding private key MUST be presented with the access
	// token when it is used by a client. Additionally, the token's `token_type` will be set to 'DPoP'.
	//
	DpopKeyThumbprint *string `json:"dpopKeyThumbprint,omitzero" form:"name=dpopKeyThumbprint"`
	// The authorization details. This represents the value of the `authorization_details`
	// request parameter in the preceding device authorization request which is defined in
	// "OAuth 2.0 Rich Authorization Requests".
	//
	AuthorizationDetails *AuthzDetails `json:"authorizationDetails,omitzero" form:"name=authorizationDetails,json"`
	// The value of the resources to associate with the token. This property represents the value of
	// one or more `resource` request parameters which is defined in "RFC8707 Resource Indicators for
	// OAuth 2.0".
	//
	Resources []string `json:"resources,omitzero" form:"name=resources"`
	// the flag which indicates whether the access token is for an external
	// attachment.
	//
	ForExternalAttachment *bool `json:"forExternalAttachment,omitzero" form:"name=forExternalAttachment"`
	// Additional claims that are added to the payload part of the JWT access token.
	//
	JwtAtClaims *string `json:"jwtAtClaims,omitzero" form:"name=jwtAtClaims"`
	// The Authentication Context Class Reference of the user authentication that the authorization server performed
	// during the course of issuing the access token.
	//
	Acr *string `json:"acr,omitzero" form:"name=acr"`
	// The time when the user authentication was performed during the course of issuing the access token.
	//
	AuthTime *int64 `json:"authTime,omitzero" form:"name=authTime"`
	// Flag which indicates whether the entity ID of the client was used when the request for the access token was made.
	//
	ClientEntityIDUsed *bool `json:"clientEntityIdUsed,omitzero" form:"name=clientEntityIdUsed"`
	// The client Identifier associated with the newly issued access token.
	//
	ClientIdentifier *string `json:"clientIdentifier,omitzero" form:"name=clientIdentifier"`
	// The session ID, which is the ID of the user's authentication session, associated with a newly
	// created access token.
	//
	SessionID *string `json:"sessionId,omitzero" form:"name=sessionId"`
	// Flag indicating whether a metadata document was used to resolve client metadata for this request.
	//
	// When `true`, the client metadata was retrieved via the [OAuth Client ID Metadata Document](https://datatracker.ietf.org/doc/draft-ietf-oauth-client-id-metadata-document/) (CIMD) mechanism rather than from the Authlete database.
	//
	MetadataDocumentUsed *bool `json:"metadataDocumentUsed,omitzero" form:"name=metadataDocumentUsed"`
}

func (t TokenCreateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TokenCreateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TokenCreateRequest) GetGrantType() GrantType {
	if t == nil {
		return GrantType("")
	}
	return t.GrantType
}

func (t *TokenCreateRequest) GetClientID() *int64 {
	if t == nil {
		return nil
	}
	return t.ClientID
}

func (t *TokenCreateRequest) GetSubject() *string {
	if t == nil {
		return nil
	}
	return t.Subject
}

func (t *TokenCreateRequest) GetScopes() []string {
	if t == nil {
		return nil
	}
	return t.Scopes
}

func (t *TokenCreateRequest) GetAccessTokenDuration() *int64 {
	if t == nil {
		return nil
	}
	return t.AccessTokenDuration
}

func (t *TokenCreateRequest) GetRefreshTokenDuration() *int64 {
	if t == nil {
		return nil
	}
	return t.RefreshTokenDuration
}

func (t *TokenCreateRequest) GetProperties() []Property {
	if t == nil {
		return nil
	}
	return t.Properties
}

func (t *TokenCreateRequest) GetClientIDAliasUsed() *bool {
	if t == nil {
		return nil
	}
	return t.ClientIDAliasUsed
}

func (t *TokenCreateRequest) GetAccessToken() *string {
	if t == nil {
		return nil
	}
	return t.AccessToken
}

func (t *TokenCreateRequest) GetRefreshToken() *string {
	if t == nil {
		return nil
	}
	return t.RefreshToken
}

func (t *TokenCreateRequest) GetAccessTokenPersistent() *bool {
	if t == nil {
		return nil
	}
	return t.AccessTokenPersistent
}

func (t *TokenCreateRequest) GetCertificateThumbprint() *string {
	if t == nil {
		return nil
	}
	return t.CertificateThumbprint
}

func (t *TokenCreateRequest) GetDpopKeyThumbprint() *string {
	if t == nil {
		return nil
	}
	return t.DpopKeyThumbprint
}

func (t *TokenCreateRequest) GetAuthorizationDetails() *AuthzDetails {
	if t == nil {
		return nil
	}
	return t.AuthorizationDetails
}

func (t *TokenCreateRequest) GetResources() []string {
	if t == nil {
		return nil
	}
	return t.Resources
}

func (t *TokenCreateRequest) GetForExternalAttachment() *bool {
	if t == nil {
		return nil
	}
	return t.ForExternalAttachment
}

func (t *TokenCreateRequest) GetJwtAtClaims() *string {
	if t == nil {
		return nil
	}
	return t.JwtAtClaims
}

func (t *TokenCreateRequest) GetAcr() *string {
	if t == nil {
		return nil
	}
	return t.Acr
}

func (t *TokenCreateRequest) GetAuthTime() *int64 {
	if t == nil {
		return nil
	}
	return t.AuthTime
}

func (t *TokenCreateRequest) GetClientEntityIDUsed() *bool {
	if t == nil {
		return nil
	}
	return t.ClientEntityIDUsed
}

func (t *TokenCreateRequest) GetClientIdentifier() *string {
	if t == nil {
		return nil
	}
	return t.ClientIdentifier
}

func (t *TokenCreateRequest) GetSessionID() *string {
	if t == nil {
		return nil
	}
	return t.SessionID
}

func (t *TokenCreateRequest) GetMetadataDocumentUsed() *bool {
	if t == nil {
		return nil
	}
	return t.MetadataDocumentUsed
}
