// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/authlete/terraform-provider-authlete/internal/sdk/internal/utils"
)

type TokenUpdateRequest struct {
	// An access token.
	//
	AccessToken *string `json:"accessToken,omitzero" form:"name=accessToken"`
	// A new date at which the access token will expire in milliseconds since the Unix epoch (1970-01-01).
	// If the `accessTokenExpiresAt` request parameter is not included in a request or its value is 0
	// (or negative), the expiration date of the access token is not changed.
	//
	AccessTokenExpiresAt *int64 `json:"accessTokenExpiresAt,omitzero" form:"name=accessTokenExpiresAt"`
	// A new set of scopes assigned to the access token. Scopes that are not supported by the service
	// and those that the client application associated with the access token is not allowed to request
	// are ignored on the server side. If the `scopes` request parameter is not included in a request or
	// its value is `null`, the scopes of the access token are not changed. Note that `properties` parameter
	// is accepted only when `Content-Type` of the request is `application/json`, so don't use `application/x-www-form-urlencoded`
	// if you want to specify `properties`.
	//
	Scopes []string `json:"scopes,omitzero" form:"name=scopes"`
	// A new set of properties assigned to the access token. If the `properties` request parameter is
	// not included in a request or its value is null, the properties of the access token are not changed.
	//
	Properties []Property `json:"properties,omitzero" form:"name=properties,json"`
	// A boolean request parameter which indicates whether the API attempts to update the expiration
	// date of the access token when the scopes linked to the access token are changed by this request.
	//
	AccessTokenExpiresAtUpdatedOnScopeUpdate *bool `json:"accessTokenExpiresAtUpdatedOnScopeUpdate,omitzero" form:"name=accessTokenExpiresAtUpdatedOnScopeUpdate"`
	// The hash of the access token value. Used when the hash of the token is known (perhaps from lookup)
	// but the value of the token itself is not. The value of the `accessToken` parameter takes precedence.
	//
	AccessTokenHash *string `json:"accessTokenHash,omitzero" form:"name=accessTokenHash"`
	// A boolean request parameter which indicates whether to update the value of the access token in
	// the data store. If this parameter is set to `true` then a new access token value is generated
	// by the server and returned in the response.
	//
	AccessTokenValueUpdated *bool `json:"accessTokenValueUpdated,omitzero" form:"name=accessTokenValueUpdated"`
	// The flag which indicates whether the access token expires or not. By default, all access tokens
	// expire after a period of time determined by their service. If this request parameter is `true`
	// then the access token will not automatically expire and must be revoked or deleted manually at
	// the service.
	//
	// If this request parameter is `true`, the `accessTokenExpiresAt` request parameter is ignored.
	// If this request parameter is `false`, the `accessTokenExpiresAt` request parameter is processed
	// normally.
	//
	AccessTokenPersistent *bool `json:"accessTokenPersistent,omitzero" form:"name=accessTokenPersistent"`
	// The thumbprint of the MTLS certificate bound to this token. If this property is set, a certificate
	// with the corresponding value MUST be presented with the access token when it is used by a client.
	// The value of this property must be a SHA256 certificate thumbprint, base64url encoded.
	//
	CertificateThumbprint *string `json:"certificateThumbprint,omitzero" form:"name=certificateThumbprint"`
	// The thumbprint of the public key used for DPoP presentation of this token. If this property is
	// set, a DPoP proof signed with the corresponding private key MUST be presented with the access
	// token when it is used by a client. Additionally, the token's `token_type` will be set to 'DPoP'.
	//
	DpopKeyThumbprint *string `json:"dpopKeyThumbprint,omitzero" form:"name=dpopKeyThumbprint"`
	// The authorization details. This represents the value of the `authorization_details`
	// request parameter in the preceding device authorization request which is defined in
	// "OAuth 2.0 Rich Authorization Requests".
	//
	AuthorizationDetails *AuthzDetails `json:"authorizationDetails,omitzero" form:"name=authorizationDetails,json"`
	// the flag which indicates whether the access token is for an external
	// attachment.
	//
	ForExternalAttachment *bool `json:"forExternalAttachment,omitzero" form:"name=forExternalAttachment"`
	// A new date at which the access token will expire in milliseconds since the Unix epoch (1970-01-01).
	// If the `refreshTokenExpiresAt` request parameter is not included in a request or its value is 0
	// (or negative), the expiration date of the refresh token is not changed.
	//
	RefreshTokenExpiresAt *int64 `json:"refreshTokenExpiresAt,omitzero" form:"name=refreshTokenExpiresAt"`
	// A boolean request parameter which indicates whether the API attempts to update the expiration
	// date of the refresh token when the scopes linked to the refresh token are changed by this request.
	//
	RefreshTokenExpiresAtUpdatedOnScopeUpdate *bool `json:"refreshTokenExpiresAtUpdatedOnScopeUpdate,omitzero" form:"name=refreshTokenExpiresAtUpdatedOnScopeUpdate"`
	// The token identifier.
	//
	TokenID *string `json:"tokenId,omitzero" form:"name=tokenId"`
}

func (t TokenUpdateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TokenUpdateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TokenUpdateRequest) GetAccessToken() *string {
	if t == nil {
		return nil
	}
	return t.AccessToken
}

func (t *TokenUpdateRequest) GetAccessTokenExpiresAt() *int64 {
	if t == nil {
		return nil
	}
	return t.AccessTokenExpiresAt
}

func (t *TokenUpdateRequest) GetScopes() []string {
	if t == nil {
		return nil
	}
	return t.Scopes
}

func (t *TokenUpdateRequest) GetProperties() []Property {
	if t == nil {
		return nil
	}
	return t.Properties
}

func (t *TokenUpdateRequest) GetAccessTokenExpiresAtUpdatedOnScopeUpdate() *bool {
	if t == nil {
		return nil
	}
	return t.AccessTokenExpiresAtUpdatedOnScopeUpdate
}

func (t *TokenUpdateRequest) GetAccessTokenHash() *string {
	if t == nil {
		return nil
	}
	return t.AccessTokenHash
}

func (t *TokenUpdateRequest) GetAccessTokenValueUpdated() *bool {
	if t == nil {
		return nil
	}
	return t.AccessTokenValueUpdated
}

func (t *TokenUpdateRequest) GetAccessTokenPersistent() *bool {
	if t == nil {
		return nil
	}
	return t.AccessTokenPersistent
}

func (t *TokenUpdateRequest) GetCertificateThumbprint() *string {
	if t == nil {
		return nil
	}
	return t.CertificateThumbprint
}

func (t *TokenUpdateRequest) GetDpopKeyThumbprint() *string {
	if t == nil {
		return nil
	}
	return t.DpopKeyThumbprint
}

func (t *TokenUpdateRequest) GetAuthorizationDetails() *AuthzDetails {
	if t == nil {
		return nil
	}
	return t.AuthorizationDetails
}

func (t *TokenUpdateRequest) GetForExternalAttachment() *bool {
	if t == nil {
		return nil
	}
	return t.ForExternalAttachment
}

func (t *TokenUpdateRequest) GetRefreshTokenExpiresAt() *int64 {
	if t == nil {
		return nil
	}
	return t.RefreshTokenExpiresAt
}

func (t *TokenUpdateRequest) GetRefreshTokenExpiresAtUpdatedOnScopeUpdate() *bool {
	if t == nil {
		return nil
	}
	return t.RefreshTokenExpiresAtUpdatedOnScopeUpdate
}

func (t *TokenUpdateRequest) GetTokenID() *string {
	if t == nil {
		return nil
	}
	return t.TokenID
}
