// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/authlete/terraform-provider-authlete/internal/sdk/internal/utils"
)

type TokenRequest struct {
	// OAuth 2.0 token request parameters which are the request parameters that the OAuth 2.0 token endpoint of the authorization server
	// implementation received from the client application.
	//
	// The value of parameters is the entire entity body (which is formatted in `application/x-www-form-urlencoded`) of the request from
	// the client application.
	//
	Parameters string `json:"parameters" form:"name=parameters"`
	// The client ID extracted from `Authorization` header of the token request from the client application.
	//
	// If the token endpoint of the authorization server implementation supports basic authentication as
	// a means of client authentication, and the request from the client application contained its client ID
	// in `Authorization` header, the value should be extracted and set to this parameter.
	//
	ClientID *string `json:"clientId,omitzero" form:"name=clientId"`
	// The client secret extracted from `Authorization` header of the token request from the client application.
	//
	// If the token endpoint of the authorization server implementation supports basic authentication as a means of
	// client authentication, and the request from the client application contained its client secret in `Authorization` header,
	// the value should be extracted and set to this parameter.
	//
	ClientSecret *string `json:"clientSecret,omitzero" form:"name=clientSecret"`
	// The client certificate from the MTLS of the token request from the client application.
	ClientCertificate *string `json:"clientCertificate,omitzero" form:"name=clientCertificate"`
	// The certificate path presented by the client during client authentication. These certificates are strings in PEM format.
	//
	ClientCertificatePath []string `json:"clientCertificatePath,omitzero" form:"name=clientCertificatePath"`
	// Extra properties to associate with an access token. See [Extra Properties](https://www.authlete.com/developers/definitive_guide/extra_properties/)
	// for details.
	//
	Properties []Property `json:"properties,omitzero" form:"name=properties,json"`
	// `DPoP` header presented by the client during the request to the token endpoint.
	//
	// The header contains a signed JWT which includes the public key that is paired with the private key used to sign the JWT.
	// See [OAuth 2.0 Demonstration of Proof-of-Possession at the Application Layer (DPoP)](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop)
	// for details.
	//
	Dpop *string `json:"dpop,omitzero" form:"name=dpop"`
	// HTTP method of the token request. This field is used to validate the `DPoP` header.
	//
	// In normal cases, the value is `POST`. When this parameter is omitted, `POST` is used as the default value.
	// See [OAuth 2.0 Demonstration of Proof-of-Possession at the Application Layer (DPoP)](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop)
	// for details.
	//
	Htm *string `json:"htm,omitzero" form:"name=htm"`
	// URL of the token endpoint. This field is used to validate the `DPoP` header.
	//
	// If this parameter is omitted, the `tokenEndpoint` property of the Service is used as the default value.
	// See [OAuth 2.0 Demonstration of Proof-of-Possession at the Application Layer (DPoP)](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop)
	// for details.
	//
	Htu *string `json:"htu,omitzero" form:"name=htu"`
	// The representation of an access token that may be issued as a result of the Authlete API call.
	//
	AccessToken *string `json:"accessToken,omitzero" form:"name=accessToken"`
	// Additional claims that are added to the payload part of the JWT access token.
	//
	// Effective only in the client_credentials grant flow (and the Native SSO branch of Token Exchange). For other grant flows, set additional JWT claims via the corresponding API: /auth/authorization/issue (authorization_code), /auth/backchannel/authentication/complete (CIBA), /auth/device/complete (device_code). The parameter is silently ignored when sent with other grants.
	//
	JwtAtClaims *string `json:"jwtAtClaims,omitzero" form:"name=jwtAtClaims"`
	// The value of the `OAuth-Client-Attestation` HTTP header, which is defined in the specification
	// of [OAuth 2.0 Attestation-Based Client Authentication](https://datatracker.ietf.org/doc/draft-ietf-oauth-attestation-based-client-auth/).
	//
	OauthClientAttestation *string `json:"oauthClientAttestation,omitzero" form:"name=oauthClientAttestation"`
	// The value of the `OAuth-Client-Attestation-PoP` HTTP header, which is defined in the specification
	// of [OAuth 2.0 Attestation-Based Client Authentication](https://datatracker.ietf.org/doc/draft-ietf-oauth-attestation-based-client-auth/).
	//
	OauthClientAttestationPop *string `json:"oauthClientAttestationPop,omitzero" form:"name=oauthClientAttestationPop"`
	// The duration (in seconds) of the access token that may be issued as a result of the Authlete
	// API call.
	//
	// When this request parameter holds a positive integer, it is used as the duration of the access
	// token in. In other cases, this request parameter is ignored.
	//
	AccessTokenDuration *int64 `json:"accessTokenDuration,omitzero" form:"name=accessTokenDuration"`
	// The duration (in seconds) of the refresh token that may be issued as a result of the Authlete
	// API call.
	//
	// When this request parameter holds a positive integer, it is used as the duration of the refresh
	// token in. In other cases, this request parameter is ignored.
	//
	RefreshTokenDuration *int64 `json:"refreshTokenDuration,omitzero" form:"name=refreshTokenDuration"`
	// The flag indicating whether to require the DPoP proof JWT to include the `nonce` claim. Even if
	// the service's `dpopNonceRequired` property is `false`, calling the `/auth/token` API with this
	// `dpopNonceRequired` parameter `true` will force the Authlete API to check whether the DPoP proof
	// JWT includes the expected `nonce` value.
	//
	DpopNonceRequired *bool `json:"dpopNonceRequired,omitzero" form:"name=dpopNonceRequired"`
	// Options for [OAuth Client ID Metadata Document](https://datatracker.ietf.org/doc/draft-ietf-oauth-client-id-metadata-document/) (CIMD).
	//
	// These options allow per-request control over CIMD behavior, taking precedence over service-level configuration when provided.
	//
	CimdOptions *CimdOptions `json:"cimdOptions,omitzero" form:"name=cimdOptions,json"`
}

func (t TokenRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TokenRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TokenRequest) GetParameters() string {
	if t == nil {
		return ""
	}
	return t.Parameters
}

func (t *TokenRequest) GetClientID() *string {
	if t == nil {
		return nil
	}
	return t.ClientID
}

func (t *TokenRequest) GetClientSecret() *string {
	if t == nil {
		return nil
	}
	return t.ClientSecret
}

func (t *TokenRequest) GetClientCertificate() *string {
	if t == nil {
		return nil
	}
	return t.ClientCertificate
}

func (t *TokenRequest) GetClientCertificatePath() []string {
	if t == nil {
		return nil
	}
	return t.ClientCertificatePath
}

func (t *TokenRequest) GetProperties() []Property {
	if t == nil {
		return nil
	}
	return t.Properties
}

func (t *TokenRequest) GetDpop() *string {
	if t == nil {
		return nil
	}
	return t.Dpop
}

func (t *TokenRequest) GetHtm() *string {
	if t == nil {
		return nil
	}
	return t.Htm
}

func (t *TokenRequest) GetHtu() *string {
	if t == nil {
		return nil
	}
	return t.Htu
}

func (t *TokenRequest) GetAccessToken() *string {
	if t == nil {
		return nil
	}
	return t.AccessToken
}

func (t *TokenRequest) GetJwtAtClaims() *string {
	if t == nil {
		return nil
	}
	return t.JwtAtClaims
}

func (t *TokenRequest) GetOauthClientAttestation() *string {
	if t == nil {
		return nil
	}
	return t.OauthClientAttestation
}

func (t *TokenRequest) GetOauthClientAttestationPop() *string {
	if t == nil {
		return nil
	}
	return t.OauthClientAttestationPop
}

func (t *TokenRequest) GetAccessTokenDuration() *int64 {
	if t == nil {
		return nil
	}
	return t.AccessTokenDuration
}

func (t *TokenRequest) GetRefreshTokenDuration() *int64 {
	if t == nil {
		return nil
	}
	return t.RefreshTokenDuration
}

func (t *TokenRequest) GetDpopNonceRequired() *bool {
	if t == nil {
		return nil
	}
	return t.DpopNonceRequired
}

func (t *TokenRequest) GetCimdOptions() *CimdOptions {
	if t == nil {
		return nil
	}
	return t.CimdOptions
}
