// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: daee422edf7f

package shared

type TokenRevokeResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The number of tokens revoked.
	//
	// If the target has more than 20 tokens, the response `count` will be 20 and the remainder is left untouched. To fully wipe them, call the endpoint repeatedly until `count` returns 0.
	//
	Count *int64 `json:"count,omitzero"`
}

func (t *TokenRevokeResponse) GetResultCode() *string {
	if t == nil {
		return nil
	}
	return t.ResultCode
}

func (t *TokenRevokeResponse) GetResultMessage() *string {
	if t == nil {
		return nil
	}
	return t.ResultMessage
}

func (t *TokenRevokeResponse) GetCount() *int64 {
	if t == nil {
		return nil
	}
	return t.Count
}
