// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
)

// UserinfoResponseAction - The next action that the authorization server implementation should take.
type UserinfoResponseAction string

const (
	UserinfoResponseActionInternalServerError UserinfoResponseAction = "INTERNAL_SERVER_ERROR"
	UserinfoResponseActionBadRequest          UserinfoResponseAction = "BAD_REQUEST"
	UserinfoResponseActionUnauthorized        UserinfoResponseAction = "UNAUTHORIZED"
	UserinfoResponseActionForbidden           UserinfoResponseAction = "FORBIDDEN"
	UserinfoResponseActionOk                  UserinfoResponseAction = "OK"
)

func (e UserinfoResponseAction) ToPointer() *UserinfoResponseAction {
	return &e
}
func (e *UserinfoResponseAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "INTERNAL_SERVER_ERROR":
		fallthrough
	case "BAD_REQUEST":
		fallthrough
	case "UNAUTHORIZED":
		fallthrough
	case "FORBIDDEN":
		fallthrough
	case "OK":
		*e = UserinfoResponseAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UserinfoResponseAction: %v", v)
	}
}

type UserinfoResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the authorization server implementation should take.
	Action *UserinfoResponseAction `json:"action,omitzero"`
	// The list of claims that the client application requests to be embedded in the ID token.
	//
	Claims []string `json:"claims,omitzero"`
	// The ID of the client application which is associated with the access token.
	//
	ClientID *int64 `json:"clientId,omitzero"`
	// The client ID alias when the authorization request for the access token was made.
	//
	ClientIDAlias *string `json:"clientIdAlias,omitzero"`
	// The flag which indicates whether the client ID alias was used when the authorization
	// request for the access token was made.
	//
	ClientIDAliasUsed *bool `json:"clientIdAliasUsed,omitzero"`
	// The content that the authorization server implementation can use as the value of `WWW-Authenticate`
	// header on errors.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
	// The scopes covered by the access token.
	//
	Scopes []string `json:"scopes,omitzero"`
	// The subject (= resource owner's ID).
	//
	Subject *string `json:"subject,omitzero"`
	// The access token that came along with the userinfo request.
	//
	Token *string `json:"token,omitzero"`
	// The extra properties associated with the access token.
	//
	Properties []Property `json:"properties,omitzero"`
	// The value of the `userinfo` property in the `claims` request parameter or in the `claims` property in an authorization request object.
	//
	UserInfoClaims *string `json:"userInfoClaims,omitzero"`
	// The attributes of this service that the client application belongs to.
	//
	ServiceAttributes []Pair `json:"serviceAttributes,omitzero"`
	// The attributes of the client.
	//
	ClientAttributes []Pair `json:"clientAttributes,omitzero"`
	// the claims that the user has consented for the client application
	// to know.
	//
	ConsentedClaims []string `json:"consentedClaims,omitzero"`
	// Get names of claims that are requested indirectly by *"transformed
	// claims"*.
	// A client application can request *"transformed claims"* by adding
	// names of transformed claims in the `claims` request parameter.
	// The following is an example of the `claims` request parameter
	// that requests a predefined transformed claim named `18_or_over`
	// and a transformed claim named `nationality_usa` to be embedded
	// in the response from the userinfo endpoint.
	// ```json
	// &#123;
	// "transformed_claims": &#123;
	// "nationality_usa": &#123;
	// "claim": "nationalities",
	// "fn": [
	// [ "eq", "USA" ],
	// "any"
	// ]
	// &#125;
	// &#125;,
	// "userinfo": &#123;
	// "::18_or_over": null,
	// ":nationality_usa": null
	// &#125;
	// &#125;
	// ```
	// The example above assumes that a transformed claim named `18_or_over`
	// is predefined by the authorization server like below.
	// ```json
	// &#123;
	// "18_or_over": &#123;
	// "claim": "birthdate",
	// "fn": [
	// "years_ago",
	// [ "gte", 18 ]
	// ]
	// &#125;
	// &#125;
	// ```
	// In the example, the `nationalities` claim is requested indirectly
	// by the `nationality_usa` transformed claim. Likewise, the
	// `birthdate` claim is requested indirectly by the `18_or_over`
	// transformed claim.
	// When the `claims` request parameter of an authorization request is
	// like the example above, this `requestedClaimsForTx` property will
	// hold the following value.
	// ```json
	// [ "birthdate", "nationalities" ]
	// ```
	// It is expected that the authorization server implementation prepares values
	// of the listed claims and passes them as the value of the `claimsForTx`
	// request parameter when it calls the `/api/auth/userinfo/issue` API. The following
	// is an example of the value of the `claimsForTx` request parameter.
	// ```json
	// &#123;
	// "birthdate": "1970-01-23",
	// "nationalities": [ "DEU", "USA" ]
	// &#125;
	// ```
	//
	RequestedClaimsForTx []string `json:"requestedClaimsForTx,omitzero"`
	// Names of verified claims that will be referenced when transformed claims are computed.
	//
	RequestedVerifiedClaimsForTx [][]string `json:"requestedVerifiedClaimsForTx,omitzero"`
	// the value of the `transformed_claims` property in the `claims` request
	// parameter of an authorization request or in the `claims` property in a
	// request object.
	//
	TransformedClaims *string `json:"transformedClaims,omitzero"`
	// The entity ID of the client.
	//
	ClientEntityID *string `json:"clientEntityId,omitzero"`
	// Flag which indicates whether the entity ID of the client was used when the request for the access token was made.
	//
	ClientEntityIDUsed *bool `json:"clientEntityIdUsed,omitzero"`
	// The expected nonce value for DPoP proof JWT, which should be used
	// as the value of the `DPoP-Nonce` HTTP header.
	//
	DpopNonce *string `json:"dpopNonce,omitzero"`
	// The location of the client's metadata document that was used to resolve client metadata.
	//
	// This property is set when client metadata was retrieved via the [OAuth Client ID Metadata Document](https://datatracker.ietf.org/doc/draft-ietf-oauth-client-id-metadata-document/) (CIMD) mechanism.
	//
	MetadataDocumentLocation *string `json:"metadataDocumentLocation,omitzero"`
	// Flag indicating whether a metadata document was used to resolve client metadata for this request.
	//
	// When `true`, the client metadata was retrieved via the CIMD mechanism rather than from the Authlete database.
	//
	MetadataDocumentUsed *bool `json:"metadataDocumentUsed,omitzero"`
}

func (u UserinfoResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserinfoResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UserinfoResponse) GetResultCode() *string {
	if u == nil {
		return nil
	}
	return u.ResultCode
}

func (u *UserinfoResponse) GetResultMessage() *string {
	if u == nil {
		return nil
	}
	return u.ResultMessage
}

func (u *UserinfoResponse) GetAction() *UserinfoResponseAction {
	if u == nil {
		return nil
	}
	return u.Action
}

func (u *UserinfoResponse) GetClaims() []string {
	if u == nil {
		return nil
	}
	return u.Claims
}

func (u *UserinfoResponse) GetClientID() *int64 {
	if u == nil {
		return nil
	}
	return u.ClientID
}

func (u *UserinfoResponse) GetClientIDAlias() *string {
	if u == nil {
		return nil
	}
	return u.ClientIDAlias
}

func (u *UserinfoResponse) GetClientIDAliasUsed() *bool {
	if u == nil {
		return nil
	}
	return u.ClientIDAliasUsed
}

func (u *UserinfoResponse) GetResponseContent() *string {
	if u == nil {
		return nil
	}
	return u.ResponseContent
}

func (u *UserinfoResponse) GetScopes() []string {
	if u == nil {
		return nil
	}
	return u.Scopes
}

func (u *UserinfoResponse) GetSubject() *string {
	if u == nil {
		return nil
	}
	return u.Subject
}

func (u *UserinfoResponse) GetToken() *string {
	if u == nil {
		return nil
	}
	return u.Token
}

func (u *UserinfoResponse) GetProperties() []Property {
	if u == nil {
		return nil
	}
	return u.Properties
}

func (u *UserinfoResponse) GetUserInfoClaims() *string {
	if u == nil {
		return nil
	}
	return u.UserInfoClaims
}

func (u *UserinfoResponse) GetServiceAttributes() []Pair {
	if u == nil {
		return nil
	}
	return u.ServiceAttributes
}

func (u *UserinfoResponse) GetClientAttributes() []Pair {
	if u == nil {
		return nil
	}
	return u.ClientAttributes
}

func (u *UserinfoResponse) GetConsentedClaims() []string {
	if u == nil {
		return nil
	}
	return u.ConsentedClaims
}

func (u *UserinfoResponse) GetRequestedClaimsForTx() []string {
	if u == nil {
		return nil
	}
	return u.RequestedClaimsForTx
}

func (u *UserinfoResponse) GetRequestedVerifiedClaimsForTx() [][]string {
	if u == nil {
		return nil
	}
	return u.RequestedVerifiedClaimsForTx
}

func (u *UserinfoResponse) GetTransformedClaims() *string {
	if u == nil {
		return nil
	}
	return u.TransformedClaims
}

func (u *UserinfoResponse) GetClientEntityID() *string {
	if u == nil {
		return nil
	}
	return u.ClientEntityID
}

func (u *UserinfoResponse) GetClientEntityIDUsed() *bool {
	if u == nil {
		return nil
	}
	return u.ClientEntityIDUsed
}

func (u *UserinfoResponse) GetDpopNonce() *string {
	if u == nil {
		return nil
	}
	return u.DpopNonce
}

func (u *UserinfoResponse) GetMetadataDocumentLocation() *string {
	if u == nil {
		return nil
	}
	return u.MetadataDocumentLocation
}

func (u *UserinfoResponse) GetMetadataDocumentUsed() *bool {
	if u == nil {
		return nil
	}
	return u.MetadataDocumentUsed
}
