// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
)

type UserinfoIssueRequest struct {
	// The access token that has been passed to the userinfo endpoint by the client application. In other words,
	// the access token which was contained in the userinfo request.
	//
	Token string `json:"token" form:"name=token"`
	// Claims in JSON format. As for the format, see [OpenID Connect Core 1.0, 5.1. Standard Claims](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims).
	//
	Claims *string `json:"claims,omitzero" form:"name=claims"`
	// The value of the `sub` claim. If the value of this request parameter is not empty, it is used as the value of
	// the `sub` claim. Otherwise, the value of the subject associated with the access token is used.
	//
	Sub *string `json:"sub,omitzero" form:"name=sub"`
	// Claim key-value pairs that are used to compute transformed claims.
	//
	ClaimsForTx *string `json:"claimsForTx,omitzero" form:"name=claimsForTx"`
	// The Signature header value from the request.
	//
	RequestSignature *string `json:"requestSignature,omitzero" form:"name=requestSignature"`
	// HTTP headers to be included in processing the signature. If this is a signed request, this must include the
	// Signature and Signature-Input headers, as well as any additional headers covered by the signature.
	//
	Headers []Pair `json:"headers,omitzero" form:"name=headers,json"`
	// Values of verified claims requested indirectly by "transformed claims".
	//
	VerifiedClaimsForTx []string `json:"verifiedClaimsForTx,omitzero" form:"name=verifiedClaimsForTx"`
}

func (u UserinfoIssueRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserinfoIssueRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UserinfoIssueRequest) GetToken() string {
	if u == nil {
		return ""
	}
	return u.Token
}

func (u *UserinfoIssueRequest) GetClaims() *string {
	if u == nil {
		return nil
	}
	return u.Claims
}

func (u *UserinfoIssueRequest) GetSub() *string {
	if u == nil {
		return nil
	}
	return u.Sub
}

func (u *UserinfoIssueRequest) GetClaimsForTx() *string {
	if u == nil {
		return nil
	}
	return u.ClaimsForTx
}

func (u *UserinfoIssueRequest) GetRequestSignature() *string {
	if u == nil {
		return nil
	}
	return u.RequestSignature
}

func (u *UserinfoIssueRequest) GetHeaders() []Pair {
	if u == nil {
		return nil
	}
	return u.Headers
}

func (u *UserinfoIssueRequest) GetVerifiedClaimsForTx() []string {
	if u == nil {
		return nil
	}
	return u.VerifiedClaimsForTx
}
