// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 10bb66c921c1

package shared

import (
	"encoding/json"
	"fmt"
)

// UserinfoIssueResponseAction - The next action that the authorization server implementation should take.
type UserinfoIssueResponseAction string

const (
	UserinfoIssueResponseActionInternalServerError UserinfoIssueResponseAction = "INTERNAL_SERVER_ERROR"
	UserinfoIssueResponseActionBadRequest          UserinfoIssueResponseAction = "BAD_REQUEST"
	UserinfoIssueResponseActionUnauthorized        UserinfoIssueResponseAction = "UNAUTHORIZED"
	UserinfoIssueResponseActionForbidden           UserinfoIssueResponseAction = "FORBIDDEN"
	UserinfoIssueResponseActionJSON                UserinfoIssueResponseAction = "JSON"
	UserinfoIssueResponseActionJwt                 UserinfoIssueResponseAction = "JWT"
)

func (e UserinfoIssueResponseAction) ToPointer() *UserinfoIssueResponseAction {
	return &e
}
func (e *UserinfoIssueResponseAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "INTERNAL_SERVER_ERROR":
		fallthrough
	case "BAD_REQUEST":
		fallthrough
	case "UNAUTHORIZED":
		fallthrough
	case "FORBIDDEN":
		fallthrough
	case "JSON":
		fallthrough
	case "JWT":
		*e = UserinfoIssueResponseAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UserinfoIssueResponseAction: %v", v)
	}
}

type UserinfoIssueResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the authorization server implementation should take.
	Action *UserinfoIssueResponseAction `json:"action,omitzero"`
	// The content that the authorization server implementation can use as the value of `WWW-Authenticate`
	// header on errors.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
	// The signature header of the response message.
	//
	Signature *string `json:"signature,omitzero"`
	// The signature-input header of the response message
	//
	SignatureInput *string `json:"signatureInput,omitzero"`
	// The content-digest header of the response message
	//
	ContentDigest *string `json:"contentDigest,omitzero"`
}

func (u *UserinfoIssueResponse) GetResultCode() *string {
	if u == nil {
		return nil
	}
	return u.ResultCode
}

func (u *UserinfoIssueResponse) GetResultMessage() *string {
	if u == nil {
		return nil
	}
	return u.ResultMessage
}

func (u *UserinfoIssueResponse) GetAction() *UserinfoIssueResponseAction {
	if u == nil {
		return nil
	}
	return u.Action
}

func (u *UserinfoIssueResponse) GetResponseContent() *string {
	if u == nil {
		return nil
	}
	return u.ResponseContent
}

func (u *UserinfoIssueResponse) GetSignature() *string {
	if u == nil {
		return nil
	}
	return u.Signature
}

func (u *UserinfoIssueResponse) GetSignatureInput() *string {
	if u == nil {
		return nil
	}
	return u.SignatureInput
}

func (u *UserinfoIssueResponse) GetContentDigest() *string {
	if u == nil {
		return nil
	}
	return u.ContentDigest
}
