// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 236763adc4be

package shared

type VciDeferredParseRequest struct {
	// The access token that came along with the deferred credential request.
	AccessToken *string `json:"accessToken,omitzero" form:"name=accessToken"`
	// The message body of the deferred credential request.
	RequestContent *string `json:"requestContent,omitzero" form:"name=requestContent"`
}

func (v *VciDeferredParseRequest) GetAccessToken() *string {
	if v == nil {
		return nil
	}
	return v.AccessToken
}

func (v *VciDeferredParseRequest) GetRequestContent() *string {
	if v == nil {
		return nil
	}
	return v.RequestContent
}
