// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// VciJwksResponseAction - The next action that the implementation of the JWK Set document
// endpoint of the credential issuer should take after getting a
// response from Authlete's `/vci/jwks` API.
type VciJwksResponseAction string

const (
	VciJwksResponseActionOk                  VciJwksResponseAction = "OK"
	VciJwksResponseActionNotFound            VciJwksResponseAction = "NOT_FOUND"
	VciJwksResponseActionInternalServerError VciJwksResponseAction = "INTERNAL_SERVER_ERROR"
)

func (e VciJwksResponseAction) ToPointer() *VciJwksResponseAction {
	return &e
}
func (e *VciJwksResponseAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OK":
		fallthrough
	case "NOT_FOUND":
		fallthrough
	case "INTERNAL_SERVER_ERROR":
		*e = VciJwksResponseAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VciJwksResponseAction: %v", v)
	}
}

type VciJwksResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the implementation of the JWK Set document
	// endpoint of the credential issuer should take after getting a
	// response from Authlete's `/vci/jwks` API.
	//
	Action *VciJwksResponseAction `json:"action,omitzero"`
	// Get the content that the implementation of the credential issuer
	// metadata endpoint should use when it constructs a response.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
}

func (v *VciJwksResponse) GetResultCode() *string {
	if v == nil {
		return nil
	}
	return v.ResultCode
}

func (v *VciJwksResponse) GetResultMessage() *string {
	if v == nil {
		return nil
	}
	return v.ResultMessage
}

func (v *VciJwksResponse) GetAction() *VciJwksResponseAction {
	if v == nil {
		return nil
	}
	return v.Action
}

func (v *VciJwksResponse) GetResponseContent() *string {
	if v == nil {
		return nil
	}
	return v.ResponseContent
}
