// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 69c1d1e8cdc3

package shared

type VciJwksRequest struct {
	// The flag indicating whether the metadata is written in the pretty
	// format or not.
	//
	Pretty bool `json:"pretty" form:"name=pretty"`
}

func (v *VciJwksRequest) GetPretty() bool {
	if v == nil {
		return false
	}
	return v.Pretty
}
