// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a18e01862caf

package shared

import (
	"encoding/json"
	"fmt"
)

// VciSingleIssueResponseAction - The next action that the implementation of the credential endpoint
// should take.
type VciSingleIssueResponseAction string

const (
	VciSingleIssueResponseActionOk                  VciSingleIssueResponseAction = "OK"
	VciSingleIssueResponseActionOkJwt               VciSingleIssueResponseAction = "OK_JWT"
	VciSingleIssueResponseActionAccepted            VciSingleIssueResponseAction = "ACCEPTED"
	VciSingleIssueResponseActionAcceptedJwt         VciSingleIssueResponseAction = "ACCEPTED_JWT"
	VciSingleIssueResponseActionBadRequest          VciSingleIssueResponseAction = "BAD_REQUEST"
	VciSingleIssueResponseActionUnauthorized        VciSingleIssueResponseAction = "UNAUTHORIZED"
	VciSingleIssueResponseActionForbidden           VciSingleIssueResponseAction = "FORBIDDEN"
	VciSingleIssueResponseActionInternalServerError VciSingleIssueResponseAction = "INTERNAL_SERVER_ERROR"
	VciSingleIssueResponseActionCallerError         VciSingleIssueResponseAction = "CALLER_ERROR"
)

func (e VciSingleIssueResponseAction) ToPointer() *VciSingleIssueResponseAction {
	return &e
}
func (e *VciSingleIssueResponseAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OK":
		fallthrough
	case "OK_JWT":
		fallthrough
	case "ACCEPTED":
		fallthrough
	case "ACCEPTED_JWT":
		fallthrough
	case "BAD_REQUEST":
		fallthrough
	case "UNAUTHORIZED":
		fallthrough
	case "FORBIDDEN":
		fallthrough
	case "INTERNAL_SERVER_ERROR":
		fallthrough
	case "CALLER_ERROR":
		*e = VciSingleIssueResponseAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VciSingleIssueResponseAction: %v", v)
	}
}

type VciSingleIssueResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the implementation of the credential endpoint
	// should take.
	//
	Action *VciSingleIssueResponseAction `json:"action,omitzero"`
	// The content of the response that the implementation of the credential
	// endpoint should return.
	//
	ResponseContent *string `json:"responseContent,omitzero"`
	// The issued transaction ID.
	//
	TransactionID *string `json:"transactionId,omitzero"`
}

func (v *VciSingleIssueResponse) GetResultCode() *string {
	if v == nil {
		return nil
	}
	return v.ResultCode
}

func (v *VciSingleIssueResponse) GetResultMessage() *string {
	if v == nil {
		return nil
	}
	return v.ResultMessage
}

func (v *VciSingleIssueResponse) GetAction() *VciSingleIssueResponseAction {
	if v == nil {
		return nil
	}
	return v.Action
}

func (v *VciSingleIssueResponse) GetResponseContent() *string {
	if v == nil {
		return nil
	}
	return v.ResponseContent
}

func (v *VciSingleIssueResponse) GetTransactionID() *string {
	if v == nil {
		return nil
	}
	return v.TransactionID
}
