// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8d1eb77412c8

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/internal/utils"
)

// VciSingleParseResponseAction - The next action that the credential endpoint should take.
type VciSingleParseResponseAction string

const (
	VciSingleParseResponseActionOk                  VciSingleParseResponseAction = "OK"
	VciSingleParseResponseActionBadRequest          VciSingleParseResponseAction = "BAD_REQUEST"
	VciSingleParseResponseActionUnauthorized        VciSingleParseResponseAction = "UNAUTHORIZED"
	VciSingleParseResponseActionForbidden           VciSingleParseResponseAction = "FORBIDDEN"
	VciSingleParseResponseActionInternalServerError VciSingleParseResponseAction = "INTERNAL_SERVER_ERROR"
)

func (e VciSingleParseResponseAction) ToPointer() *VciSingleParseResponseAction {
	return &e
}
func (e *VciSingleParseResponseAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OK":
		fallthrough
	case "BAD_REQUEST":
		fallthrough
	case "UNAUTHORIZED":
		fallthrough
	case "FORBIDDEN":
		fallthrough
	case "INTERNAL_SERVER_ERROR":
		*e = VciSingleParseResponseAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VciSingleParseResponseAction: %v", v)
	}
}

type VciSingleParseResponse struct {
	// The code which represents the result of the API call.
	ResultCode *string `json:"resultCode,omitzero"`
	// A short message which explains the result of the API call.
	ResultMessage *string `json:"resultMessage,omitzero"`
	// The next action that the credential endpoint should take.
	Action *VciSingleParseResponseAction `json:"action,omitzero"`
	// The content of the response to the request sender.
	ResponseContent *string                `json:"responseContent,omitzero"`
	Info            *CredentialRequestInfo `json:"info,omitzero"`
}

func (v VciSingleParseResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VciSingleParseResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VciSingleParseResponse) GetResultCode() *string {
	if v == nil {
		return nil
	}
	return v.ResultCode
}

func (v *VciSingleParseResponse) GetResultMessage() *string {
	if v == nil {
		return nil
	}
	return v.ResultMessage
}

func (v *VciSingleParseResponse) GetAction() *VciSingleParseResponseAction {
	if v == nil {
		return nil
	}
	return v.Action
}

func (v *VciSingleParseResponse) GetResponseContent() *string {
	if v == nil {
		return nil
	}
	return v.ResponseContent
}

func (v *VciSingleParseResponse) GetInfo() *CredentialRequestInfo {
	if v == nil {
		return nil
	}
	return v.Info
}
