// Hand-written. Not generated by Speakeasy.
package customtypes

import (
	"context"
	"testing"
)

func TestJWKSSemanticEquals(t *testing.T) {
	for name, tc := range map[string]struct {
		a, b string
		want bool
	}{
		// The real case: Authlete strips whitespace and reorders members.
		"formatting and key order differ": {
			a:    "{\n  \"keys\": [\n    {\n      \"kty\": \"RSA\",\n      \"kid\": \"k1\"\n    }\n  ]\n}",
			b:    `{"keys":[{"kid":"k1","kty":"RSA"}]}`,
			want: true,
		},
		"identical":            {a: `{"keys":[]}`, b: `{"keys":[]}`, want: true},
		"different key id":     {a: `{"keys":[{"kid":"k1"}]}`, b: `{"keys":[{"kid":"k2"}]}`, want: false},
		"extra key in set":     {a: `{"keys":[{"kid":"k1"}]}`, b: `{"keys":[{"kid":"k1"},{"kid":"k2"}]}`, want: false},
		"key order in array":   {a: `{"keys":[{"kid":"a"},{"kid":"b"}]}`, b: `{"keys":[{"kid":"b"},{"kid":"a"}]}`, want: false},
		"both unparseable":     {a: `not json`, b: `not json`, want: true},
		"one unparseable":      {a: `{"keys":[]}`, b: `not json`, want: false},
		"empty against object": {a: ``, b: `{"keys":[]}`, want: false},
	} {
		t.Run(name, func(t *testing.T) {
			got, diags := NewJWKSValue(tc.a).StringSemanticEquals(context.Background(), NewJWKSValue(tc.b))
			if diags.HasError() {
				t.Fatalf("unexpected diagnostics: %v", diags)
			}
			if got != tc.want {
				t.Errorf("semantic equality = %v, want %v", got, tc.want)
			}
		})
	}
}
