// Hand-written. Not generated by Speakeasy.
//
// Converts a PEM-encoded key into a JWK. Authlete models a JWK Set as an opaque
// JSON string, so without this a practitioner has to produce that JSON with
// external tooling and paste it into their configuration.
//
// Why a function and not a "generate" flag
// ----------------------------------------
// The published hand-written provider generates key material inside the
// resource. That cannot be expressed as a Terraform function, because functions
// must be deterministic: Terraform calls them during both plan and apply, so a
// function returning fresh random bytes would produce a different key on every
// call and the plan would never match the apply.
//
// Converting a PEM to a JWK *is* deterministic, so the split is:
//
//	resource "tls_private_key" "signing" {           # generates, holds lifecycle
//	  algorithm = "RSA"
//	  rsa_bits  = 2048
//	}
//
//	locals {
//	  signing_jwk = provider::authlete::jwk_from_pem(
//	    tls_private_key.signing.private_key_pem, "signing-key-1", "RS256", "sig")
//	}
//
// Key generation and its state handling stay with hashicorp/tls, which already
// solves them; this supplies only the transformation Authlete needs.
package functions

import (
	"context"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rsa"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"math/big"

	"github.com/hashicorp/terraform-plugin-framework/function"
)

var _ function.Function = (*JWKFromPEMFunction)(nil)

type JWKFromPEMFunction struct{}

func NewJWKFromPEMFunction() function.Function { return &JWKFromPEMFunction{} }

func (f *JWKFromPEMFunction) Metadata(_ context.Context, _ function.MetadataRequest, resp *function.MetadataResponse) {
	resp.Name = "jwk_from_pem"
}

func (f *JWKFromPEMFunction) Definition(_ context.Context, _ function.DefinitionRequest, resp *function.DefinitionResponse) {
	resp.Definition = function.Definition{
		Summary: "Convert a PEM-encoded key into a JWK",
		MarkdownDescription: "Converts a PEM-encoded RSA, ECDSA or Ed25519 key into a JWK, returned as a JSON string.\n\n" +
			"Pass a **private** key PEM for a service's signing keys, or a **public** key PEM for a client's " +
			"published keys — the output contains exactly what the input holds.\n\n" +
			"Assemble a JWK Set with `jsonencode`:\n\n" +
			"```terraform\n" +
			"jwks = jsonencode({\n" +
			"  keys = [jsondecode(provider::authlete::jwk_from_pem(\n" +
			"    tls_private_key.signing.private_key_pem, \"signing-key-1\", \"RS256\", \"sig\"))]\n" +
			"})\n" +
			"```",
		Parameters: []function.Parameter{
			function.StringParameter{
				Name:                "pem_key",
				MarkdownDescription: "PEM-encoded key. PKCS#1, PKCS#8, SEC1 and PKIX public keys are all accepted.",
			},
			function.StringParameter{
				Name:                "kid",
				MarkdownDescription: "Key ID. Authlete uses this to select a key, so keep it stable.",
			},
			function.StringParameter{
				Name:                "alg",
				MarkdownDescription: "Algorithm this key is for, such as `RS256`, `ES256` or `EdDSA`.",
			},
			function.StringParameter{
				Name:                "use",
				MarkdownDescription: "Intended use: `sig` for signing or `enc` for encryption.",
			},
		},
		Return: function.StringReturn{},
	}
}

func (f *JWKFromPEMFunction) Run(ctx context.Context, req function.RunRequest, resp *function.RunResponse) {
	var pemKey, kid, alg, use string

	resp.Error = function.ConcatFuncErrors(resp.Error,
		req.Arguments.Get(ctx, &pemKey, &kid, &alg, &use))
	if resp.Error != nil {
		return
	}

	jwk, err := jwkFromPEM(pemKey, kid, alg, use)
	if err != nil {
		resp.Error = function.ConcatFuncErrors(resp.Error, function.NewFuncError(err.Error()))
		return
	}

	encoded, err := json.Marshal(jwk)
	if err != nil {
		resp.Error = function.ConcatFuncErrors(resp.Error, function.NewFuncError(err.Error()))
		return
	}

	resp.Error = function.ConcatFuncErrors(resp.Error, resp.Result.Set(ctx, string(encoded)))
}

// --- conversion --------------------------------------------------------------

func b64u(b []byte) string { return base64.RawURLEncoding.EncodeToString(b) }

// padded renders a big.Int as a fixed-width big-endian octet string, which is
// what RFC 7518 requires. Trimming leading zeroes instead would produce a JWK
// some libraries reject.
func padded(i *big.Int, size int) string {
	b := i.Bytes()
	if len(b) >= size {
		return b64u(b)
	}
	out := make([]byte, size)
	copy(out[size-len(b):], b)
	return b64u(out)
}

func jwkFromPEM(pemKey, kid, alg, use string) (map[string]string, error) {
	block, _ := pem.Decode([]byte(pemKey))
	if block == nil {
		return nil, fmt.Errorf("jwk_from_pem: pem_key is not PEM-encoded; expected a block such as %q or %q",
			"-----BEGIN PRIVATE KEY-----", "-----BEGIN PUBLIC KEY-----")
	}

	key, err := parsePEMBlock(block)
	if err != nil {
		return nil, fmt.Errorf("jwk_from_pem: could not parse %q block: %w", block.Type, err)
	}

	jwk, err := keyToJWK(key)
	if err != nil {
		return nil, fmt.Errorf("jwk_from_pem: %w", err)
	}

	jwk["kid"] = kid
	jwk["alg"] = alg
	jwk["use"] = use
	return jwk, nil
}

func parsePEMBlock(block *pem.Block) (any, error) {
	// Try each form rather than trusting the block label, which is not always
	// accurate in keys produced by other tools.
	if k, err := x509.ParsePKCS8PrivateKey(block.Bytes); err == nil {
		return k, nil
	}
	if k, err := x509.ParsePKCS1PrivateKey(block.Bytes); err == nil {
		return k, nil
	}
	if k, err := x509.ParseECPrivateKey(block.Bytes); err == nil {
		return k, nil
	}
	if k, err := x509.ParsePKIXPublicKey(block.Bytes); err == nil {
		return k, nil
	}
	if k, err := x509.ParsePKCS1PublicKey(block.Bytes); err == nil {
		return k, nil
	}
	return nil, fmt.Errorf("unrecognised key format")
}

func keyToJWK(key any) (map[string]string, error) {
	switch k := key.(type) {
	case *rsa.PrivateKey:
		jwk := rsaPublicJWK(&k.PublicKey)
		size := (k.N.BitLen() + 7) / 8
		half := (size + 1) / 2
		jwk["d"] = padded(k.D, size)
		jwk["p"] = padded(k.Primes[0], half)
		jwk["q"] = padded(k.Primes[1], half)
		jwk["dp"] = padded(k.Precomputed.Dp, half)
		jwk["dq"] = padded(k.Precomputed.Dq, half)
		jwk["qi"] = padded(k.Precomputed.Qinv, half)
		return jwk, nil

	case *rsa.PublicKey:
		return rsaPublicJWK(k), nil

	case *ecdsa.PrivateKey:
		jwk, err := ecPublicJWK(&k.PublicKey)
		if err != nil {
			return nil, err
		}
		jwk["d"] = padded(k.D, (k.Curve.Params().BitSize+7)/8)
		return jwk, nil

	case *ecdsa.PublicKey:
		return ecPublicJWK(k)

	case ed25519.PrivateKey:
		return map[string]string{
			"kty": "OKP", "crv": "Ed25519",
			"x": b64u(k.Public().(ed25519.PublicKey)),
			"d": b64u(k.Seed()),
		}, nil

	case ed25519.PublicKey:
		return map[string]string{"kty": "OKP", "crv": "Ed25519", "x": b64u(k)}, nil
	}

	return nil, fmt.Errorf("unsupported key type %T; RSA, ECDSA and Ed25519 are supported", key)
}

func rsaPublicJWK(k *rsa.PublicKey) map[string]string {
	return map[string]string{
		"kty": "RSA",
		"n":   b64u(k.N.Bytes()),
		"e":   b64u(big.NewInt(int64(k.E)).Bytes()),
	}
}

func ecPublicJWK(k *ecdsa.PublicKey) (map[string]string, error) {
	var crv string
	switch k.Curve {
	case elliptic.P256():
		crv = "P-256"
	case elliptic.P384():
		crv = "P-384"
	case elliptic.P521():
		crv = "P-521"
	default:
		return nil, fmt.Errorf("unsupported curve %s; P-256, P-384 and P-521 are supported", k.Curve.Params().Name)
	}

	size := (k.Curve.Params().BitSize + 7) / 8
	return map[string]string{
		"kty": "EC",
		"crv": crv,
		"x":   padded(k.X, size),
		"y":   padded(k.Y, size),
	}, nil
}
