// Hand-written. Not generated by Speakeasy.
package functions

import (
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"math/big"
	"strings"
	"testing"
)

func encodePEM(t *testing.T, typ string, der []byte) string {
	t.Helper()
	return string(pem.EncodeToMemory(&pem.Block{Type: typ, Bytes: der}))
}

func decodeB64u(t *testing.T, s string) []byte {
	t.Helper()
	b, err := base64.RawURLEncoding.DecodeString(s)
	if err != nil {
		t.Fatalf("value is not unpadded base64url: %q", s)
	}
	return b
}

func TestRSAPrivateKeyRoundTrips(t *testing.T) {
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		t.Fatal(err)
	}
	der, _ := x509.MarshalPKCS8PrivateKey(key)

	jwk, err := jwkFromPEM(encodePEM(t, "PRIVATE KEY", der), "k1", "RS256", "sig")
	if err != nil {
		t.Fatal(err)
	}

	if jwk["kty"] != "RSA" || jwk["kid"] != "k1" || jwk["alg"] != "RS256" || jwk["use"] != "sig" {
		t.Fatalf("metadata wrong: %v", jwk)
	}

	// Reconstructing the key from the JWK must yield the original, which is the
	// only check that proves the encoding is actually usable.
	n := new(big.Int).SetBytes(decodeB64u(t, jwk["n"]))
	d := new(big.Int).SetBytes(decodeB64u(t, jwk["d"]))
	e := new(big.Int).SetBytes(decodeB64u(t, jwk["e"]))
	if n.Cmp(key.N) != 0 {
		t.Error("modulus does not round-trip")
	}
	if d.Cmp(key.D) != 0 {
		t.Error("private exponent does not round-trip")
	}
	if e.Int64() != int64(key.E) {
		t.Errorf("public exponent = %d, want %d", e.Int64(), key.E)
	}

	// RFC 7518 wants fixed-width octet strings, not trimmed integers.
	if got, want := len(decodeB64u(t, jwk["n"])), 256; got != want {
		t.Errorf("n is %d bytes, want %d", got, want)
	}
	if got, want := len(decodeB64u(t, jwk["p"])), 128; got != want {
		t.Errorf("p is %d bytes, want %d", got, want)
	}
}

func TestRSAPublicKeyOmitsPrivateParts(t *testing.T) {
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		t.Fatal(err)
	}
	der, _ := x509.MarshalPKIXPublicKey(&key.PublicKey)

	jwk, err := jwkFromPEM(encodePEM(t, "PUBLIC KEY", der), "k1", "RS256", "sig")
	if err != nil {
		t.Fatal(err)
	}

	for _, secret := range []string{"d", "p", "q", "dp", "dq", "qi"} {
		if _, present := jwk[secret]; present {
			t.Errorf("public key JWK leaked private component %q", secret)
		}
	}
	if jwk["n"] == "" || jwk["e"] == "" {
		t.Error("public components missing")
	}
}

func TestECCurvesAreNamedCorrectly(t *testing.T) {
	for _, tc := range []struct {
		curve elliptic.Curve
		crv   string
		size  int
	}{
		{elliptic.P256(), "P-256", 32},
		{elliptic.P384(), "P-384", 48},
		{elliptic.P521(), "P-521", 66},
	} {
		key, err := ecdsa.GenerateKey(tc.curve, rand.Reader)
		if err != nil {
			t.Fatal(err)
		}
		der, _ := x509.MarshalPKCS8PrivateKey(key)

		jwk, err := jwkFromPEM(encodePEM(t, "PRIVATE KEY", der), "k1", "ES256", "sig")
		if err != nil {
			t.Fatal(err)
		}
		if jwk["kty"] != "EC" || jwk["crv"] != tc.crv {
			t.Errorf("got kty=%s crv=%s, want EC/%s", jwk["kty"], jwk["crv"], tc.crv)
		}
		// Coordinates must be padded to the curve width; P-521 in particular
		// produces short values often enough for this to matter.
		for _, c := range []string{"x", "y", "d"} {
			if got := len(decodeB64u(t, jwk[c])); got != tc.size {
				t.Errorf("%s: %s is %d bytes, want %d", tc.crv, c, got, tc.size)
			}
		}
	}
}

func TestEd25519(t *testing.T) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	der, _ := x509.MarshalPKCS8PrivateKey(priv)

	jwk, err := jwkFromPEM(encodePEM(t, "PRIVATE KEY", der), "k1", "EdDSA", "sig")
	if err != nil {
		t.Fatal(err)
	}
	if jwk["kty"] != "OKP" || jwk["crv"] != "Ed25519" {
		t.Fatalf("got kty=%s crv=%s, want OKP/Ed25519", jwk["kty"], jwk["crv"])
	}
	if got := decodeB64u(t, jwk["x"]); string(got) != string(pub) {
		t.Error("public key does not round-trip")
	}
	if got := len(decodeB64u(t, jwk["d"])); got != ed25519.SeedSize {
		t.Errorf("d is %d bytes, want the %d-byte seed", got, ed25519.SeedSize)
	}
}

func TestPKCS1AndSEC1AreAccepted(t *testing.T) {
	rsaKey, _ := rsa.GenerateKey(rand.Reader, 2048)
	if _, err := jwkFromPEM(encodePEM(t, "RSA PRIVATE KEY", x509.MarshalPKCS1PrivateKey(rsaKey)), "k", "RS256", "sig"); err != nil {
		t.Errorf("PKCS#1 rejected: %v", err)
	}

	ecKey, _ := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	der, _ := x509.MarshalECPrivateKey(ecKey)
	if _, err := jwkFromPEM(encodePEM(t, "EC PRIVATE KEY", der), "k", "ES256", "sig"); err != nil {
		t.Errorf("SEC1 rejected: %v", err)
	}
}

func TestErrorsAreActionable(t *testing.T) {
	if _, err := jwkFromPEM("clearly not a key", "k", "RS256", "sig"); err == nil {
		t.Error("expected an error for non-PEM input")
	} else if !strings.Contains(err.Error(), "BEGIN") {
		t.Errorf("error should show the expected PEM shape, got: %v", err)
	}

	if _, err := jwkFromPEM(encodePEM(t, "PRIVATE KEY", []byte("garbage")), "k", "RS256", "sig"); err == nil {
		t.Error("expected an error for a PEM block with unparseable contents")
	}
}

func TestDeterministic(t *testing.T) {
	key, _ := rsa.GenerateKey(rand.Reader, 2048)
	der, _ := x509.MarshalPKCS8PrivateKey(key)
	p := encodePEM(t, "PRIVATE KEY", der)

	// Terraform calls functions during plan and again during apply. If the two
	// results differed the plan would never match the apply.
	first, err := jwkFromPEM(p, "k1", "RS256", "sig")
	if err != nil {
		t.Fatal(err)
	}
	second, _ := jwkFromPEM(p, "k1", "RS256", "sig")

	for k, v := range first {
		if second[k] != v {
			t.Fatalf("field %q differs between calls", k)
		}
	}
}
