// Hand-written. Not generated by Speakeasy.
//
// Catches a provider configuration whose server_url and api_server_id describe
// different deployments.
//
// The two are used for different calls: server_url is the regional cluster that
// serves reads and updates, api_server_id tells the IdP which cluster to create
// the service on. When they disagree, the service is created on one cluster and
// then looked for on another -- so `apply` succeeds and the very next refresh
// fails with a 403, leaving a service Terraform can neither read nor delete.
//
// Observed while testing: server_url pointing at US with api_server_id set to
// Japan's 53285 created the service on JP, and `terraform destroy` then failed
// against US. Changing server_url to JP made it succeed immediately.
//
// This is deliberately narrow. It only fires when the cluster is one the
// provider knows and the configured id contradicts it. An unrecognised host --
// Dedicated Cloud, On-Premise, pre-production -- is never flagged, because those
// are exactly the deployments that must set api_server_id by hand and whose
// correct value only the operator knows. Values arriving from the environment
// are not visible here, so a missing api_server_id is never treated as an error.
//
// ConfigValidators is declared on AuthleteProvider from this file rather than in
// the generated provider.go: Go allows methods on a type to live in any file of
// the same package, so this adds behaviour without another hand edit.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/provider"
)

var _ provider.ProviderWithConfigValidators = (*AuthleteProvider)(nil)

func (p *AuthleteProvider) ConfigValidators(_ context.Context) []provider.ConfigValidator {
	return []provider.ConfigValidator{clusterConsistency{}}
}

type clusterConsistency struct{}

func (clusterConsistency) Description(_ context.Context) string {
	return "server_url and api_server_id must describe the same Authlete deployment"
}

func (v clusterConsistency) MarkdownDescription(ctx context.Context) string {
	return v.Description(ctx)
}

func (clusterConsistency) ValidateProvider(ctx context.Context, req provider.ValidateConfigRequest, resp *provider.ValidateConfigResponse) {
	var data AuthleteProviderModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Only compare when both are set in configuration. Either may legitimately
	// come from the environment instead, which is not visible from here.
	if data.ServerURL.IsNull() || data.ServerURL.IsUnknown() ||
		data.APIServerID.IsNull() || data.APIServerID.IsUnknown() {
		return
	}

	expected, known := APIServerIDForServerURL(data.ServerURL.ValueString())
	if !known {
		// A deployment the provider does not know. The operator's value is the
		// only source of truth, so there is nothing to check against.
		return
	}

	configured := data.APIServerID.ValueInt64()
	if configured == expected {
		return
	}

	resp.Diagnostics.AddAttributeError(
		path.Root("api_server_id"),
		"api_server_id does not match server_url",
		fmt.Sprintf(
			"server_url is %q, whose API server id is %d, but api_server_id is set to %d.\n\n"+
				"These are used for different calls: server_url serves reads and updates, "+
				"while api_server_id tells the IdP which cluster to create the service on. "+
				"Mismatched, a service is created on one cluster and looked for on another, "+
				"so apply succeeds and the next refresh fails with a 403 -- leaving a service "+
				"Terraform can neither read nor delete.\n\n"+
				"Set both to the same deployment, or omit api_server_id to use %d.",
			data.ServerURL.ValueString(), expected, configured, expected),
	)
}
