// Hand-written. Not generated by Speakeasy.
//
// Guards the plan-time checking of enum list elements.
//
// The wiring is x-speakeasy-plan-validators in the overlay, so an overlay edit
// could drop it silently: the provider still builds and every other test passes,
// and the only symptom is a typo reaching Authlete and costing a minute of
// retries followed by a generic 500.
package provider

import (
	"testing"

	"github.com/authlete/terraform-provider-authlete/internal/provider/validators"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func TestEnumListsAreValidated(t *testing.T) {
	for name, res := range map[string]resource.Resource{
		"authlete_service": NewServiceResource(),
		"authlete_client":  NewClientResource(),
	} {
		attrs := resourceSchema(t, res).Attributes
		for attrName := range validators.EnumLists {
			attr, ok := attrs[attrName]
			if !ok {
				continue // the table covers both resources; not every name is on both
			}
			list, ok := attr.(schema.ListAttribute)
			if !ok {
				continue // read-only ones are not settable, so nothing to validate
			}
			if len(list.Validators) == 0 {
				t.Errorf("%s.%s accepts any string.\n\n"+
					"A misspelled value reaches Authlete unchecked, costs about a minute of "+
					"retries, and returns a generic 500 naming neither the attribute nor the "+
					"value.\n\nRestore the x-speakeasy-plan-validators entry for this property "+
					"in .speakeasy/terraform_overlay.yaml.", name, attrName)
			}
		}
	}
}

// The permitted values come from the SDK's generated enum types, so they track
// the specification. This checks that delegation actually works rather than
// silently accepting everything.
func TestPermittedValuesComeFromTheSpec(t *testing.T) {
	for _, tc := range []struct {
		attribute string
		value     string
		want      bool
	}{
		{"supported_grant_types", "AUTHORIZATION_CODE", true},
		{"supported_grant_types", "NOT_A_GRANT", false},
		{"fapi_modes", "FAPI1_ADVANCED", true},
		{"fapi_modes", "FAPI1_ADVANCE", false},
		{"supported_displays", "PAGE", true},
		{"supported_displays", "page", false},
	} {
		got, known := validators.Accepts(tc.attribute, tc.value)
		if !known {
			t.Errorf("%s is not in the validation table", tc.attribute)
			continue
		}
		if got != tc.want {
			t.Errorf("Accepts(%q, %q) = %v, want %v", tc.attribute, tc.value, got, tc.want)
		}
	}
}

// An attribute absent from the table must pass rather than be rejected. Two
// lists are deliberately absent because their enums are inline in the
// specification, so no Go type is generated to check against.
func TestUnknownAttributesAreNotRejected(t *testing.T) {
	ok, known := validators.Accepts("response_modes", "ANYTHING")
	if known {
		t.Error("response_modes is in the table; its enum is inline in the spec, so a " +
			"hand-copied list would eventually reject a value Authlete had added")
	}
	if !ok {
		t.Error("an attribute outside the table must be accepted, not rejected")
	}
}
