// Hand-written. Not generated by Speakeasy, and deliberately kept in its own
// file so that persistent edits to generated files stay as small as possible.
//
// Why this exists
// ---------------
// Authlete creates and deletes services through its IdP, which is a different
// host from the regional API cluster. The OpenAPI document declares that host as
// a fixed URL, so Speakeasy resolves it at generation time and bakes it into the
// call. There is no override path: SupportedOptionServerURL is not offered for
// those operations, and per-operation OpenAPI server variables are resolved to
// their default rather than surfaced as configuration.
//
// The practical effect is that only Authlete's shared cloud works. Dedicated
// Cloud and On-Premise deployments run their own IdP and cannot be reached at
// all, so those customers can neither create nor delete a service.
//
// This mirrors the approach taken for the TypeScript SDK in authlete/
// authlete-typescript-sdk#36: intercept at the HTTP layer and match requests by
// URL origin against the generated constant, so the match tracks the spec
// instead of duplicating a hostname.
package provider

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/speakeasy/terraform-provider-authlete/internal/sdk/models/operations"
)

// apiServerIDByHost maps an Authlete cluster to the numeric API server ID the
// IdP uses to identify it. The official hand-written SDKs inject this so callers
// never see it; a generated provider has no such table, which is why customers
// would otherwise have to look the number up and type it themselves.
//
// Self-managed deployments are not in this map and must set api_server_id
// explicitly on the resource.
var apiServerIDByHost = map[string]int64{
	"us.authlete.com": 76281,
	"jp.authlete.com": 53285,
	"eu.authlete.com": 63294,
	"br.authlete.com": 47363,
}

// APIServerIDForServerURL returns the API server ID for a cluster URL, and
// whether one is known. An unrecognised host is not an error: self-managed
// deployments legitimately have an ID that only the operator knows.
func APIServerIDForServerURL(serverURL string) (int64, bool) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return 0, false
	}
	id, ok := apiServerIDByHost[strings.ToLower(u.Hostname())]
	return id, ok
}

// defaultIdpOrigin is the IdP origin the generator baked in, read back from the
// generated operation rather than written out again here. If the spec changes
// the IdP host, this follows it.
func defaultIdpOrigin() string {
	raw := operations.ServiceCreateIdpAPIServerList[operations.ServiceCreateIdpAPIServerIdp]
	// The generated value may contain server-variable placeholders; substituting
	// nothing leaves the literal default, which is what we want to compare.
	u, err := url.Parse(raw)
	if err != nil || u.Host == "" {
		return ""
	}
	return u.Scheme + "://" + u.Host
}

// idpRoutingTransport rewrites requests bound for Authlete's default IdP origin
// so they reach a customer's own IdP instead. Every other request is passed
// through untouched.
type idpRoutingTransport struct {
	// idpHost is the replacement IdP host, optionally including a scheme and
	// port. Empty means no rewriting is performed.
	idpHost string
	// apiServerID is injected into IdP request bodies that omit it. Zero means
	// no injection, which is correct for a self-managed deployment whose ID we
	// cannot derive.
	apiServerID int64
	next        http.RoundTripper
}

// NewIdpRoutingTransport wraps next so that requests to Authlete's default IdP
// origin are redirected to idpHost, and so that IdP request bodies omitting
// apiServerId have apiServerID filled in.
//
// When neither applies the inner transport is returned unchanged, so the
// shared-cloud path keeps exactly its generated behaviour.
func NewIdpRoutingTransport(idpHost string, apiServerID int64, next http.RoundTripper) http.RoundTripper {
	idpHost = strings.TrimSpace(idpHost)
	if idpHost == "" && apiServerID == 0 {
		return next
	}
	if next == nil {
		next = http.DefaultTransport
	}
	return &idpRoutingTransport{idpHost: idpHost, apiServerID: apiServerID, next: next}
}

// idpBodyPaths are the IdP operations whose request body carries apiServerId.
var idpBodyPaths = map[string]bool{
	"/api/service":        true,
	"/api/service/remove": true,
}

func (t *idpRoutingTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	origin := defaultIdpOrigin()
	if origin == "" || req.URL == nil {
		return t.next.RoundTrip(req)
	}

	if req.URL.Scheme+"://"+req.URL.Host != origin {
		return t.next.RoundTrip(req)
	}

	// RoundTrip must not modify the request it is given.
	cloned := req.Clone(req.Context())

	if t.idpHost != "" {
		target := t.idpHost
		if !strings.Contains(target, "://") {
			target = "https://" + target
		}
		u, err := url.Parse(target)
		if err != nil || u.Host == "" {
			// A malformed override should not silently send IdP traffic to
			// Authlete's shared cloud, so fail loudly rather than passing through.
			return nil, &url.Error{Op: "parse", URL: t.idpHost, Err: err}
		}
		cloned.URL.Scheme = u.Scheme
		cloned.URL.Host = u.Host
		cloned.Host = u.Host
	}

	if t.apiServerID != 0 && idpBodyPaths[req.URL.Path] {
		if err := injectAPIServerID(cloned, t.apiServerID); err != nil {
			return nil, err
		}
	}

	return t.next.RoundTrip(cloned)
}

// injectAPIServerID adds apiServerId to a JSON request body that does not
// already carry a usable one. A value the caller set explicitly is never
// overwritten. A body that is absent or not an object is left alone, so a
// malformed request fails at the API with its own error rather than here.
func injectAPIServerID(req *http.Request, id int64) error {
	if req.Body == nil {
		return nil
	}

	raw, err := io.ReadAll(req.Body)
	_ = req.Body.Close()
	if err != nil {
		return err
	}

	restore := func(b []byte) {
		req.Body = io.NopCloser(bytes.NewReader(b))
		req.ContentLength = int64(len(b))
		req.GetBody = func() (io.ReadCloser, error) {
			return io.NopCloser(bytes.NewReader(b)), nil
		}
	}

	var body map[string]json.RawMessage
	if err := json.Unmarshal(raw, &body); err != nil {
		restore(raw)
		return nil
	}

	if existing, ok := body["apiServerId"]; ok {
		var n json.Number
		if err := json.Unmarshal(existing, &n); err == nil && n.String() != "0" && n.String() != "" {
			restore(raw)
			return nil
		}
	}

	body["apiServerId"], err = json.Marshal(id)
	if err != nil {
		restore(raw)
		return nil
	}

	updated, err := json.Marshal(body)
	if err != nil {
		restore(raw)
		return nil
	}

	restore(updated)
	return nil
}
