// Hand-written. Not generated by Speakeasy.
package provider

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// capture records the URL each request was actually sent to, without a network.
type capture struct{ got []string }

func (c *capture) RoundTrip(req *http.Request) (*http.Response, error) {
	c.got = append(c.got, req.URL.Scheme+"://"+req.URL.Host+req.URL.Path)
	return &http.Response{
		StatusCode: http.StatusOK,
		Body:       http.NoBody,
		Request:    req,
		Header:     make(http.Header),
	}, nil
}

func send(t *testing.T, rt http.RoundTripper, rawURL string) {
	t.Helper()
	req := httptest.NewRequest(http.MethodPost, rawURL, nil)
	req.RequestURI = ""
	if _, err := rt.RoundTrip(req); err != nil {
		t.Fatalf("RoundTrip(%s): %v", rawURL, err)
	}
}

func TestDefaultIdpOriginTracksGeneratedSpec(t *testing.T) {
	if got := defaultIdpOrigin(); got == "" {
		t.Fatal("defaultIdpOrigin() is empty; the generated server list no longer parses, " +
			"so IdP requests would never be matched and on-premise routing would silently break")
	}
}

func TestUnsetIdpHostIsAPassthrough(t *testing.T) {
	inner := &capture{}
	rt := NewIdpRoutingTransport("", 0, inner)

	if rt != http.RoundTripper(inner) {
		t.Fatal("no idp_host and no apiServerId must return the inner transport unchanged, " +
			"so the shared-cloud path keeps exactly its generated behaviour")
	}
}

func TestIdpBoundRequestIsRerouted(t *testing.T) {
	inner := &capture{}
	rt := NewIdpRoutingTransport("authlete-login.example.com", 0, inner)

	send(t, rt, defaultIdpOrigin()+"/api/service")

	want := "https://authlete-login.example.com/api/service"
	if len(inner.got) != 1 || inner.got[0] != want {
		t.Fatalf("got %v, want [%s]", inner.got, want)
	}
}

func TestClusterTrafficIsUntouched(t *testing.T) {
	inner := &capture{}
	rt := NewIdpRoutingTransport("authlete-login.example.com", 0, inner)

	// A service read goes to the regional cluster, not the IdP. Rerouting it
	// would send API traffic to the IdP and break every read.
	send(t, rt, "https://jp.authlete.com/api/12345/service/get")

	want := "https://jp.authlete.com/api/12345/service/get"
	if len(inner.got) != 1 || inner.got[0] != want {
		t.Fatalf("cluster request was rewritten: got %v, want [%s]", inner.got, want)
	}
}

func TestSchemeAndPortAreHonoured(t *testing.T) {
	for _, tc := range []struct{ idpHost, want string }{
		{"idp.internal:8443", "https://idp.internal:8443/api/service"},
		{"https://idp.internal", "https://idp.internal/api/service"},
		{"http://idp.internal", "http://idp.internal/api/service"},
		{"  idp.internal  ", "https://idp.internal/api/service"},
	} {
		inner := &capture{}
		rt := NewIdpRoutingTransport(tc.idpHost, 0, inner)
		send(t, rt, defaultIdpOrigin()+"/api/service")
		if len(inner.got) != 1 || inner.got[0] != tc.want {
			t.Errorf("idp_host %q: got %v, want [%s]", tc.idpHost, inner.got, tc.want)
		}
	}
}

func TestOriginalRequestIsNotMutated(t *testing.T) {
	inner := &capture{}
	rt := NewIdpRoutingTransport("idp.internal", 0, inner)

	req := httptest.NewRequest(http.MethodPost, defaultIdpOrigin()+"/api/service", nil)
	req.RequestURI = ""
	before := req.URL.Host

	if _, err := rt.RoundTrip(req); err != nil {
		t.Fatalf("RoundTrip: %v", err)
	}
	if req.URL.Host != before {
		t.Fatalf("RoundTrip mutated the request it was given: %s -> %s", before, req.URL.Host)
	}
}

func TestAPIServerIDForServerURL(t *testing.T) {
	for _, tc := range []struct {
		url  string
		want int64
		ok   bool
	}{
		{"https://us.authlete.com", 76281, true},
		{"https://jp.authlete.com", 53285, true},
		{"https://eu.authlete.com", 63294, true},
		{"https://br.authlete.com", 47363, true},
		{"https://JP.authlete.com", 53285, true},
		{"https://jp.authlete.com:443/api", 53285, true},
		{"https://authlete.example.com", 0, false},
		{"", 0, false},
	} {
		got, ok := APIServerIDForServerURL(tc.url)
		if got != tc.want || ok != tc.ok {
			t.Errorf("APIServerIDForServerURL(%q) = (%d, %v), want (%d, %v)", tc.url, got, ok, tc.want, tc.ok)
		}
	}
}

// --- apiServerId injection ---------------------------------------------------

// bodyCapture records the request body actually sent.
type bodyCapture struct{ body string }

func (c *bodyCapture) RoundTrip(req *http.Request) (*http.Response, error) {
	if req.Body != nil {
		b, _ := io.ReadAll(req.Body)
		c.body = string(b)
	}
	return &http.Response{StatusCode: http.StatusOK, Body: http.NoBody, Request: req, Header: make(http.Header)}, nil
}

func postJSON(t *testing.T, rt http.RoundTripper, rawURL, body string) {
	t.Helper()
	req := httptest.NewRequest(http.MethodPost, rawURL, strings.NewReader(body))
	req.RequestURI = ""
	if _, err := rt.RoundTrip(req); err != nil {
		t.Fatalf("RoundTrip: %v", err)
	}
}

func decode(t *testing.T, s string) map[string]any {
	t.Helper()
	var m map[string]any
	if err := json.Unmarshal([]byte(s), &m); err != nil {
		t.Fatalf("body is not JSON: %q", s)
	}
	return m
}

func TestAPIServerIDIsInjectedWhenAbsent(t *testing.T) {
	inner := &bodyCapture{}
	rt := NewIdpRoutingTransport("", 53285, inner)

	postJSON(t, rt, defaultIdpOrigin()+"/api/service", `{"organizationId":123456789012345,"service":{"serviceName":"x"}}`)

	got := decode(t, inner.body)
	if got["apiServerId"] != float64(53285) {
		t.Fatalf("apiServerId = %v, want 53285 (body: %s)", got["apiServerId"], inner.body)
	}
	if got["organizationId"] != float64(123456789012345) {
		t.Fatalf("injection clobbered organizationId: %s", inner.body)
	}
}

func TestExplicitAPIServerIDIsNeverOverwritten(t *testing.T) {
	inner := &bodyCapture{}
	rt := NewIdpRoutingTransport("", 53285, inner)

	postJSON(t, rt, defaultIdpOrigin()+"/api/service", `{"apiServerId":99999,"organizationId":1}`)

	if got := decode(t, inner.body); got["apiServerId"] != float64(99999) {
		t.Fatalf("apiServerId = %v, want the caller's 99999", got["apiServerId"])
	}
}

func TestAPIServerIDInjectedOnRemoveToo(t *testing.T) {
	inner := &bodyCapture{}
	rt := NewIdpRoutingTransport("", 76281, inner)

	postJSON(t, rt, defaultIdpOrigin()+"/api/service/remove", `{"organizationId":1,"serviceId":2}`)

	if got := decode(t, inner.body); got["apiServerId"] != float64(76281) {
		t.Fatalf("apiServerId = %v, want 76281", got["apiServerId"])
	}
}

func TestClusterBodiesAreNotTouched(t *testing.T) {
	inner := &bodyCapture{}
	rt := NewIdpRoutingTransport("", 53285, inner)

	const body = `{"serviceName":"x"}`
	postJSON(t, rt, "https://jp.authlete.com/api/12345/service/update", body)

	if inner.body != body {
		t.Fatalf("cluster body was rewritten: %s", inner.body)
	}
}

func TestNonJSONBodyIsLeftAlone(t *testing.T) {
	inner := &bodyCapture{}
	rt := NewIdpRoutingTransport("", 53285, inner)

	const body = `not json at all`
	postJSON(t, rt, defaultIdpOrigin()+"/api/service", body)

	if inner.body != body {
		t.Fatalf("non-JSON body was altered: %s", inner.body)
	}
}
