// Hand-written. Not generated by Speakeasy.
//
// Keeps the migration failure messages honest about how to import.
//
// When state cannot be migrated, the upgraders tell the practitioner to remove
// the resource and import it again, and spell out the command. That advice is
// the only thing standing between them and a broken workspace, so it has to be
// a command that actually works.
//
// It was wrong for the client: the message gave `<service api key>/<client id>`
// while ImportState takes a JSON object. Anyone following it hit a second,
// unrelated error while recovering from the first.
//
// Rather than asserting the text, this takes the command out of the message,
// fills in the placeholders, and feeds the result to the real importer. The
// test fails if either side changes without the other.
package provider

import (
	"context"
	"regexp"
	"strings"
	"testing"

	"github.com/authlete/terraform-provider-authlete/internal/stateupgraders"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

// importIDFrom pulls the id argument out of a `terraform import <addr> <id>`
// line, stripping the single quotes a shell would.
var importLine = regexp.MustCompile(`terraform import \S+ (.+)`)

func importIDFrom(t *testing.T, message string) string {
	t.Helper()
	m := importLine.FindStringSubmatch(message)
	if m == nil {
		t.Fatalf("no `terraform import` command in the remediation message:\n\n%s", message)
	}
	return strings.Trim(strings.TrimSpace(m[1]), "'")
}

// remediationFor runs an upgrader over state it cannot migrate and returns the
// detail of the error it raises.
func remediationFor(t *testing.T, up func(context.Context, resource.UpgradeStateRequest, *resource.UpgradeStateResponse), old string) string {
	t.Helper()
	resp := &resource.UpgradeStateResponse{}
	up(context.Background(), resource.UpgradeStateRequest{
		RawState: &tfprotov6.RawState{JSON: []byte(old)},
	}, resp)
	if !resp.Diagnostics.HasError() {
		t.Fatal("expected the upgrader to refuse this state and offer remediation")
	}
	return resp.Diagnostics.Errors()[0].Detail()
}

// TestMigrationRemediationActuallyImports is the guard. The command the
// migration failure prints must be accepted by the importer it names.
func TestMigrationRemediationActuallyImports(t *testing.T) {
	t.Run("client", func(t *testing.T) {
		detail := remediationFor(t, stateupgraders.ClientStateUpgraderV0, `{"service_api_key":"8689741203439953"}`)
		id := importIDFrom(t, detail)

		// Fill in what the message leaves for the practitioner.
		id = strings.ReplaceAll(id, "<client id>", "41925176568")
		id = strings.ReplaceAll(id, "<service api key>", "8689741203439953")

		r := NewClientResource()
		sch := resourceSchema(t, r)
		resp := &resource.ImportStateResponse{
			State: tfsdk.State{
				Schema: sch,
				Raw:    tftypes.NewValue(sch.Type().TerraformType(context.Background()), nil),
			},
		}
		r.(resource.ResourceWithImportState).ImportState(context.Background(),
			resource.ImportStateRequest{ID: id}, resp)

		if resp.Diagnostics.HasError() {
			t.Errorf("the migration message tells people to run:\n\n  terraform import authlete_client.<name> %s\n\n"+
				"and the importer rejects it: %v\n\n"+
				"Someone recovering from a failed migration hits a second error while "+
				"following the advice given for the first. The client importer takes a "+
				"JSON object, not a slash-separated pair.", id, resp.Diagnostics.Errors())
		}
	})

	t.Run("service", func(t *testing.T) {
		detail := remediationFor(t, stateupgraders.ServiceStateUpgraderV0, `{"service_name":"x"}`)
		id := strings.ReplaceAll(importIDFrom(t, detail), "<service api key>", "8689741203439953")

		r := NewServiceResource()
		sch := resourceSchema(t, r)
		resp := &resource.ImportStateResponse{
			State: tfsdk.State{
				Schema: sch,
				Raw:    tftypes.NewValue(sch.Type().TerraformType(context.Background()), nil),
			},
		}
		r.(resource.ResourceWithImportState).ImportState(context.Background(),
			resource.ImportStateRequest{ID: id}, resp)

		if resp.Diagnostics.HasError() {
			t.Errorf("the migration message tells people to run:\n\n  terraform import authlete_service.<name> %s\n\n"+
				"and the importer rejects it: %v", id, resp.Diagnostics.Errors())
		}
	})
}
