// Hand-written. Not generated by Speakeasy.
//
// Guards the TF_LOG redaction. See log_redaction.go for why it exists.
//
// The pattern is the whole fix, so it is tested directly. A first attempt used
// `[^"]*` for the value and masked only a fragment of a JWK Set, because the
// value contains escaped quotes -- it looked like it worked. These cases exist
// so that failure mode cannot come back unnoticed.
package provider

import (
	"net/http"
	"strings"
	"testing"
)

func TestSecretFieldsAreRedacted(t *testing.T) {
	for _, tc := range []struct {
		name string
		body string
		gone []string // must not survive
		kept []string // must survive
	}{
		{
			name: "jwks holding JSON with escaped quotes",
			body: `{"serviceName":"svc","jwks":"{\"keys\":[{\"kid\":\"CANARY\",\"k\":\"c3VwZXItc2VjcmV0\"}]}","issuer":"https://x"}`,
			gone: []string{"CANARY", "c3VwZXItc2VjcmV0"},
			kept: []string{"serviceName", "svc", "issuer", "https://x"},
		},
		{
			name: "server-generated client secret",
			body: `{"clientId":123,"clientSecret":"7mIYLd6oisfYxgD7TS3","clientName":"app"}`,
			gone: []string{"7mIYLd6oisfYxgD7TS3"},
			kept: []string{"clientId", "123", "clientName", "app"},
		},
		{
			name: "callback secrets and api secret",
			body: `{"apiSecret":"a1","authenticationCallbackApiSecret":"b2","tokenEndpoint":"https://t"}`,
			gone: []string{`"a1"`, `"b2"`},
			kept: []string{"tokenEndpoint", "https://t"},
		},
		{
			name: "public URLs must not be redacted",
			body: `{"jwksUri":"https://x/jwks","credentialJwksUri":"https://y","federationJwks":"{\"keys\":[]}"}`,
			gone: []string{`federationJwks`},
			kept: []string{"jwksUri", "https://x/jwks", "credentialJwksUri", "https://y"},
		},
		{
			name: "a value containing an escaped backslash then a quote",
			body: `{"apiSecret":"we\\\"ird","issuer":"https://keep"}`,
			gone: []string{"ird"},
			kept: []string{"issuer", "https://keep"},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got := secretFields.ReplaceAllString(tc.body, "***")
			for _, s := range tc.gone {
				if strings.Contains(got, s) {
					t.Errorf("%q survived redaction.\n\n  in:  %s\n  out: %s\n\n"+
						"Secrets in TF_LOG=DEBUG output are readable by anyone with access to "+
						"CI logs.", s, tc.body, got)
				}
			}
			for _, s := range tc.kept {
				if !strings.Contains(got, s) {
					t.Errorf("%q was redacted but should have been kept.\n\n  in:  %s\n  out: %s\n\n"+
						"Over-redacting defeats the point: debug logs exist so support can see "+
						"what was actually sent.", s, tc.body, got)
				}
			}
		})
	}
}

// The transport must wrap unconditionally. An earlier draft put this inside
// NewIdpRoutingTransport, which returns its inner transport unchanged on the
// shared-cloud path -- so redaction would have applied only to self-managed
// deployments.
func TestRedactionWrapsEveryTransport(t *testing.T) {
	inner := &capture{}
	if rt := NewLogRedactingTransport(inner); rt == http.RoundTripper(inner) {
		t.Fatal("NewLogRedactingTransport returned its inner transport unchanged; " +
			"redaction must apply on every path, including shared cloud")
	}
}
