// Hand-written. Not generated by Speakeasy.
//
// Keeps secrets out of TF_LOG=DEBUG output.
//
// The generated logging transport in utils.go records every request and
// response body verbatim, masking only the Authorization header. So a debug run
// writes client secrets and private JWK Sets into the log in full. Marking an
// attribute sensitive does not help: that governs what Terraform prints about
// state, and nothing in the logging path consults it.
//
// This is inherited behaviour rather than a Speakeasy defect -- the transport is
// derived from terraform-plugin-sdk's helper/logging/logging_http_transport.go,
// which logs the same bodies and redacts nothing at all, not even
// Authorization. But the provider being replaced (v1.3.17) installed no logging
// transport whatsoever, so for a migrating customer this is a regression, and
// upstream is not taking new Terraform features.
//
// Rather than patch the generated file, this works through the context. The
// generated transport logs with tflog.Debug(req.Context(), ...), and tflog
// carries its masking configuration on that same context -- so a transport
// wrapped *outside* it can decide what the inner one is allowed to print.
// Nothing generated is touched, and there is nothing to re-apply after a run.
package provider

import (
	"net/http"
	"regexp"

	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// secretFields matches a JSON field whose name looks like key material,
// together with its value, so only that field is removed and the rest of the
// payload stays readable.
//
// The heuristic is on the field name, not a fixed list: anything containing
// "secret" or "password", plus anything ending in "jwks". Name-based means a
// secret field the API grows later is covered without anyone remembering to
// add it. Ending in "jwks" rather than containing it is deliberate -- it
// catches jwks, federationJwks and credentialJwks while leaving jwksUri and
// credentialJwksUri alone, which are public URLs worth seeing in a log.
//
// The value pattern is `(?:\\.|[^"\\])*` rather than `[^"]*`. A first
// attempt used the latter and failed: jwks is a string attribute holding a JWK
// Set, so its value contains escaped quotes, and a naive class stops at the
// first one and masks only a fragment. That reads as protection while leaking,
// which is worse than not redacting. This class steps over escapes.
//
// tflog replaces the entire match with ***, so the field name disappears along
// with its value. Every other field in the payload is untouched.
var secretFields = regexp.MustCompile(
	`(?i)"([a-z0-9_]*(?:secret|password)[a-z0-9_]*|[a-z0-9_]*jwks)"\s*:\s*"(?:\\.|[^"\\])*"`)

// redactingTransport installs tflog masking on the request context, so the
// generated logging transport further down the chain redacts as it writes.
type redactingTransport struct {
	next http.RoundTripper
}

// NewLogRedactingTransport wraps next so that secret values in request and
// response bodies are masked in TF_LOG output.
func NewLogRedactingTransport(next http.RoundTripper) http.RoundTripper {
	return &redactingTransport{next: next}
}

func (t *redactingTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	ctx := tflog.MaskAllFieldValuesRegexes(req.Context(), secretFields)
	return t.next.RoundTrip(req.WithContext(ctx))
}
