// Hand-written. Not generated by Speakeasy.
//
// Guards the TF_LOG redaction. See log_redaction.go for why it exists.
//
// The pattern is the whole fix, so it is tested directly. A first attempt used
// `[^"]*` for the value and masked only a fragment of a JWK Set, because the
// value contains escaped quotes -- it looked like it worked. These cases exist
// so that failure mode cannot come back unnoticed.
package provider

import (
	"net/http"
	"os"
	"strings"
	"testing"
)

func TestSecretFieldsAreRedacted(t *testing.T) {
	for _, tc := range []struct {
		name string
		body string
		gone []string // must not survive
		kept []string // must survive
	}{
		{
			name: "jwks holding JSON with escaped quotes",
			body: `{"serviceName":"svc","jwks":"{\"keys\":[{\"kid\":\"CANARY\",\"k\":\"c3VwZXItc2VjcmV0\"}]}","issuer":"https://x"}`,
			gone: []string{"CANARY", "c3VwZXItc2VjcmV0"},
			kept: []string{"serviceName", "svc", "issuer", "https://x"},
		},
		{
			name: "server-generated client secret",
			body: `{"clientId":123,"clientSecret":"7mIYLd6oisfYxgD7TS3","clientName":"app"}`,
			gone: []string{"7mIYLd6oisfYxgD7TS3"},
			kept: []string{"clientId", "123", "clientName", "app"},
		},
		{
			name: "callback secrets and api secret",
			body: `{"apiSecret":"a1","authenticationCallbackApiSecret":"b2","tokenEndpoint":"https://t"}`,
			gone: []string{`"a1"`, `"b2"`},
			kept: []string{"tokenEndpoint", "https://t"},
		},
		{
			name: "public URLs must not be redacted",
			body: `{"jwksUri":"https://x/jwks","credentialJwksUri":"https://y","federationJwks":"{\"keys\":[]}"}`,
			gone: []string{`federationJwks`},
			kept: []string{"jwksUri", "https://x/jwks", "credentialJwksUri", "https://y"},
		},
		{
			name: "a value containing an escaped backslash then a quote",
			body: `{"apiSecret":"we\\\"ird","issuer":"https://keep"}`,
			gone: []string{"ird"},
			kept: []string{"issuer", "https://keep"},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got := secretFields.ReplaceAllString(tc.body, "***")
			for _, s := range tc.gone {
				if strings.Contains(got, s) {
					t.Errorf("%q survived redaction.\n\n  in:  %s\n  out: %s\n\n"+
						"Secrets in TF_LOG=DEBUG output are readable by anyone with access to "+
						"CI logs.", s, tc.body, got)
				}
			}
			for _, s := range tc.kept {
				if !strings.Contains(got, s) {
					t.Errorf("%q was redacted but should have been kept.\n\n  in:  %s\n  out: %s\n\n"+
						"Over-redacting defeats the point: debug logs exist so support can see "+
						"what was actually sent.", s, tc.body, got)
				}
			}
		})
	}
}

// The transport must wrap unconditionally. An earlier draft put this inside
// NewIdpRoutingTransport, which returns its inner transport unchanged on the
// shared-cloud path -- so redaction would have applied only to self-managed
// deployments.
func TestRedactionWrapsEveryTransport(t *testing.T) {
	inner := &capture{}
	if rt := NewLogRedactingTransport(inner); rt == http.RoundTripper(inner) {
		t.Fatal("NewLogRedactingTransport returned its inner transport unchanged; " +
			"redaction must apply on every path, including shared cloud")
	}
}

// TestRedactionIsWiredIntoConfigure guards the wiring rather than the pattern.
//
// Every other test in this file proves the regexp masks what it should, and
// TestRedactionWrapsEveryTransport proves the constructor wraps. None of them
// notice if provider.go stops calling the constructor: the transport still
// exists, still compiles, still passes its own tests, and nothing is redacted
// because nothing installs it. TF_LOG=DEBUG then writes client secrets and
// private keys verbatim again.
//
// That edit lives in a generated file and is re-applied by
// scripts/patch-provider.sh, so it can be dropped by a regeneration. The script
// checks it too; this fails under `go test` as well, where a dropped edit is
// more likely to be noticed.
//
// Order matters as much as presence. The redacting transport installs masking
// on the request context, and the generated logging transport reads that
// context when it records bodies. Redaction has to be the outermost wrapper, so
// the context is already masked by the time anything logs.
func TestRedactionIsWiredIntoConfigure(t *testing.T) {
	src, err := os.ReadFile("provider.go")
	if err != nil {
		t.Fatalf("cannot read provider.go: %v", err)
	}
	body := string(src)

	if !strings.Contains(body, "NewLogRedactingTransport(") {
		t.Fatal("provider.go never calls NewLogRedactingTransport.\n\n" +
			"Nothing installs masking, so TF_LOG=DEBUG writes client secrets, " +
			"callback secrets and private keys verbatim into the log.\n\n" +
			"A regeneration has most likely dropped the edit. Run:\n\n" +
			"  ./scripts/patch-provider.sh")
	}

	redact := strings.Index(body, "NewLogRedactingTransport(")
	route := strings.Index(body, "NewIdpRoutingTransport(")
	if route < 0 {
		t.Fatal("provider.go never calls NewIdpRoutingTransport; run ./scripts/patch-provider.sh")
	}
	if redact > route {
		t.Error("NewLogRedactingTransport is applied inside NewIdpRoutingTransport.\n\n" +
			"Redaction installs masking on the request context, and the generated " +
			"logging transport reads that context when it records bodies. Wrapped on " +
			"the inside, the masking is installed after logging has already seen the " +
			"unmasked request.\n\n" +
			"Redaction must be the outermost transport.")
	}
}
