// Hand-written. Not generated by Speakeasy.
//
// Guards the "unset list sent as []" fix.
//
// The generated Terraform->SDK conversion builds lists with
// make([]T, 0, len(...)), which yields an empty but non-nil slice when the
// practitioner never set the attribute. The SDK tags these fields `omitzero`,
// and for a slice only nil is the zero value, so an unset list reaches the wire
// as [] rather than being omitted. Authlete applies its defaults only when a
// key is absent, so the service is created supporting nothing: plan and apply
// are both clean, and the failure appears later at runtime one error at a time
// (A015304 displays, A009305 response type, A049305 grant type).
//
// The fix is `nullable: true` on these seven properties in
// .speakeasy/terraform_overlay.yaml, which makes the generator emit the same
// nil guard it already uses for scalars.
//
// This test exists because that fix lives in the overlay, and an overlay edit
// or a generator change could quietly undo it. Nothing else would notice: the
// provider would still build, and every test that only creates resources with
// explicit values would still pass. The failure only shows up when a customer
// creates a service without listing every supported value by hand, which is
// what a minimal first config looks like.
package provider

import (
	"context"
	"encoding/json"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/types"
)

// marshalWith converts a model to its SDK input and returns the JSON body.
type converter func(t *testing.T, list []types.String) string

func serviceBody(field func(*ServiceResourceModel, []types.String)) converter {
	return func(t *testing.T, list []types.String) string {
		t.Helper()
		m := &ServiceResourceModel{}
		field(m, list)
		in, diags := m.ToSharedServiceInput(context.Background())
		if diags.HasError() {
			t.Fatalf("conversion: %v", diags)
		}
		b, err := json.Marshal(in)
		if err != nil {
			t.Fatalf("marshal: %v", err)
		}
		return string(b)
	}
}

func clientBody(field func(*ClientResourceModel, []types.String)) converter {
	return func(t *testing.T, list []types.String) string {
		t.Helper()
		m := &ClientResourceModel{}
		field(m, list)
		in, diags := m.ToSharedClientInput(context.Background())
		if diags.HasError() {
			t.Fatalf("conversion: %v", diags)
		}
		b, err := json.Marshal(in)
		if err != nil {
			t.Fatalf("marshal: %v", err)
		}
		return string(b)
	}
}

// TestOptionalArraysOmitNull is the direct guard. A null attribute must not
// appear in the request body at all, or the server skips its default.
func TestOptionalArraysOmitNull(t *testing.T) {
	for _, tc := range []struct {
		attr    string // Terraform attribute name, for the failure message
		jsonKey string // wire name, also the overlay target
		schema  string // overlay schema the target lives under
		body    converter
	}{
		{"supported_displays", "supportedDisplays", "service",
			serviceBody(func(m *ServiceResourceModel, v []types.String) { m.SupportedDisplays = v })},
		{"supported_grant_types", "supportedGrantTypes", "service",
			serviceBody(func(m *ServiceResourceModel, v []types.String) { m.SupportedGrantTypes = v })},
		{"supported_response_types", "supportedResponseTypes", "service",
			serviceBody(func(m *ServiceResourceModel, v []types.String) { m.SupportedResponseTypes = v })},
		{"supported_token_auth_methods", "supportedTokenAuthMethods", "service",
			serviceBody(func(m *ServiceResourceModel, v []types.String) { m.SupportedTokenAuthMethods = v })},
		{"supported_prompt_values", "supportedPromptValues", "service",
			serviceBody(func(m *ServiceResourceModel, v []types.String) { m.SupportedPromptValues = v })},
		{"supported_claim_types", "supportedClaimTypes", "service",
			serviceBody(func(m *ServiceResourceModel, v []types.String) { m.SupportedClaimTypes = v })},
		{"response_modes", "responseModes", "client",
			clientBody(func(m *ClientResourceModel, v []types.String) { m.ResponseModes = v })},
	} {
		t.Run(tc.attr, func(t *testing.T) {
			key := `"` + tc.jsonKey + `"`

			if body := tc.body(t, nil); strings.Contains(body, key) {
				t.Errorf("%s is null in config but %s is present in the request body.\n\n"+
					"Authlete applies its default only when the key is absent, so the "+
					"service is created supporting nothing. apply stays clean and the "+
					"failure appears later at runtime.\n\n"+
					"Restore `nullable: true` on "+
					"$.components.schemas.%s.properties.%s in "+
					".speakeasy/terraform_overlay.yaml.", tc.attr, key, tc.schema, tc.jsonKey)
			}

			// The other half of the contract: an explicit empty list still means
			// "support none" and must be sent. Dropping it would be a different
			// bug with the same single-line fix.
			if body := tc.body(t, []types.String{}); !strings.Contains(body, key) {
				t.Errorf("%s = [] was dropped from the request body.\n\n"+
					"An explicit empty list means `support none` and must reach the "+
					"server; only an unset attribute may be omitted.", tc.attr)
			}
		})
	}
}
