// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 28178886db82

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type CredentialIssuerMetadata struct {
	AuthorizationServers                           []types.String `tfsdk:"authorization_servers"`
	BatchCredentialEndpoint                        types.String   `tfsdk:"batch_credential_endpoint"`
	BatchSize                                      types.Int64    `tfsdk:"batch_size"`
	CredentialEndpoint                             types.String   `tfsdk:"credential_endpoint"`
	CredentialIssuer                               types.String   `tfsdk:"credential_issuer"`
	CredentialResponseEncryptionAlgValuesSupported []types.String `tfsdk:"credential_response_encryption_alg_values_supported"`
	CredentialResponseEncryptionEncValuesSupported []types.String `tfsdk:"credential_response_encryption_enc_values_supported"`
	CredentialResponseEncryptionZipValuesSupported []types.String `tfsdk:"credential_response_encryption_zip_values_supported"`
	CredentialsSupported                           types.String   `tfsdk:"credentials_supported"`
	DeferredCredentialEndpoint                     types.String   `tfsdk:"deferred_credential_endpoint"`
	RequireCredentialRequestEncryption             types.Bool     `tfsdk:"require_credential_request_encryption"`
	RequireCredentialResponseEncryption            types.Bool     `tfsdk:"require_credential_response_encryption"`
}
