// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a2197b857ede

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type NamedURI struct {
	Name types.String `tfsdk:"name"`
	URI  types.String `tfsdk:"uri"`
}
