// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 939b4828be02

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Scope struct {
	Attributes   []Pair        `tfsdk:"attributes"`
	DefaultEntry types.Bool    `tfsdk:"default_entry"`
	Description  types.String  `tfsdk:"description"`
	Descriptions []TaggedValue `tfsdk:"descriptions"`
	Name         types.String  `tfsdk:"name"`
}
